;;; masd.el --- Major mode for files using the MASD syntaxe
;;; Copyright 2001 by Yves Brissaud (yBr) <yves.brissaud@gmail.com>

;;; masd.el is free software distributed under the terms
;;; of the GNU General Public License, version 2 or higher.
;;; For details, see the file COPYING.

;;; This is version 1.0 of 23 October 2001.

; 1.0  :
;        Some bug are corected, like the number of spaces.
;        This version is the first distributed version.
;        There's allways the bug with A=C.B discribe in 0.2e :(
; 0.2e :
;        There's some prob with instructions like A=C.B
;        If we write A=C.B A+1.B, A+1.B is not supported
;        But if we write A=C.B  A+1.B (with 2 spaces), A+1.B is supported
;        I don't now why but I search
;        PC=(A) and PC=(C) aren't supported
;        All the other instructions are supported (If some are not, mail me :) )
; 0.2d :
;        Integration of extable, but it doesn't work very good :(
; 0.2c :
;        All the regexps are rewrite...
;        We can now write A=A+C.A or A=A+C A (and A+C.A or A+C A of course :) )
;        Support of all masd meta-instruction (all instructions I now...)
;
; 0.2, 0.2a, 0.2b :
;        Try of some regexps, but very bad result
;
; 0.1a :
;        Support of some Masd meta-instruction
;
; 0.1  :
;        First version, few instructions supported

;; Some times, you can find "chl ajout"
;; This is some added or corrections by CHL.


;;; Code :

(defvar masd-mode-syntax-table nil
  "Syntax table in use in Masd mode buffers.")

(if masd-mode-syntax-table
    ()
  (setq masd-mode-syntax-table (make-syntax-table))
  (modify-syntax-entry ?\n ">   " masd-mode-syntax-table)
  (modify-syntax-entry ?\% "<   " masd-mode-syntax-table)
  )

(defvar masd-mode-abbrev-table nil
  "Abbrev table used in Masd mode.")
(define-abbrev-table 'masd-mode-abbrev-table ())

(defconst masd-font-lock-keywords
  (eval-when-compile
    (list
       ; :GOTOL :GOLONG :GOVLNG :GOSUB :GOSBVL :GONC :GOC :GOTOC :GOTONC :GOTO :GOYES :GOINC
     (cons (concat
; chl : ajout de 'L' pour GOSUBL
	    "\\<\\(GO\\(TO\\(L\\|C\\|NC\\)?\\|L\\|VLNG\\|SBVL\\|SUBL?\\|NC\\|C\\|YES\\|INC\\)\\|"
	    "R\\(SI\\|T\\(I\\|Y\\|YES\\|N\\(\\(S\\)?\\(C\\)*\\|SXM\\|\\|YES\\|NC\\)?\\)\\)\\|"
	    "SK\\(ELSE\\|UB\\(L\\)?\\|IP\\(YES\\|NC\\|C\\|L\\)?\\|\\(N\\)?C\\)\\|"
; chl : ajout de [2-9]
	    "EXIT\\(\\(N\\)?C\\)?[2-9]?\\|"
	    "UP\\(\\(N\\)?C\\)?[2-9]?\\|"
; ajout chl
	    "DC\\(CP +[0-9A-F]+\\)?\\|CP=[0-9A-F]+\\|ECU\\|"
	    "\\)\\>"
	    "\\|{\\|}"
	    )
	   'font-lock-keyword-face)

     ; Instructions
     (cons (concat
; chl : ajouts de +
	    "\\<\\("
	    "[AC]=IN\\|"
	    "[AC]=PC\\|" "PC=[AC]\\|" "PC=([AC])\\|"
; chl : supression de A, ajout de +
	    "P=[C0]?\\(\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\)?\\|"
	    "C=P\\(\\.\\| +\\)\\([0-9]\\|1[0-6]\\)\\|"
	    "\\??\\(HST\\|P\\)=\\([0-9]\\|1[0-6]\\)\\|"
	    "C\\+P\\+1\\|"
	    "C=RSTK\\|RSTK=C\\|OUT=C\\|C=OUT\\(S\\)?\\|"
	    "[A-D]S\\([LR]\\(C\\)?\\|RB\\)\\(\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\)?\\|"
	    "BUSC[BCD]\\|SHUTDN\\|RESET\\|UNCNFG\\|CONFIG\\|C=ID\\|SREQ\\?\\|INTO\\(N\\|FF\\)\\|"
	    "SET\\(DEC\\|HEX\\)\\|CON\\|"
	    "[AC]BIT=[01]\\(\\.\\| +\\)\\([0-9]\\|1[0-6]\\)\\|"
	    "\\??\\(XM\\|S[BR]\\|MP\\)=0\\|" "CLRHST\\|"
	    "ST=[01C\\(CS\\)]\\(\\.\\| +\\)\\([0-9]\\|1[0-5]\\)\\|"
	    "\\([A-D]\\|R[0-4]\\)\\([A-D]\\|R[0-4]\\|P\\)EX\\(\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\)?\\|"
	    "CSTEX\\|C=ST\\|ST=C.X\\|"
	    "[AC]D[01]\\(XS\\|EX\\)\\|"
	    "[AC]PCEX\\(\\.\\| +\\)\\([0-9]\\|1[0-6]\\)\\|"
	    "R[0-4]=[AC]\\(\\(\\.\\| +\\)\\([0-9ABWSXMP]\\|XS\\|WP\\|1[0-6]\\)\\)?\\|"
	    "[AC]=R[0-4]\\(\\(\\.\\| +\\)\\([0-9ABWSXMP]\\|XS\\|WP\\|1[0-6]\\)\\)?\\|"
	    "\\(\\(R[0-4]\\|[AC]\\)=\\)?\\(R[0-4]\\|[AC]\\)[-\\+\\&!]\\(R[0-4]\\|[AC]\\)\\(\\.\\| +\\)\\([0-9ABWSXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "\\(D[01]=\\)?D[01][\\+-] *[0-9A-F]+\\|"
	    "D[01]=[AC]S?\\|"
	    "D[01]=\\(([245])\\)? ?[@0-9a-zA-Z\\+-\\*_\\$-]+\\|"
	    "[AC]=D\\([01]\\|AT[01]\\(\\.\\| +\\)\\([0-9ABWSXMP]\\|XS\\|WP\\|1[0-6]\\)\\)\\|"
	    "DAT[01]=[AC]\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|WP\\|1[0-6]\\)\\|"
	    "[AB]\\(=[ABC]\\)?[#\\+-\\&!][ABC]\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "D\\(=[CD]\\)?[#\\+-\\&!][CD]\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "C\\(=[ABCD]\\)?[#\\+-\\&!][ABCD]\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "\\([ABCD]=\\)?[ABCD][\\+-][0-9A-F]+\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "[A-D][#=]0\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|[0-6]\\)\\|"
	    "A=C\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "L[AC]\\(HEX\\|ASC\\)?\\((\\([1-9]\\|1[0-6]\\))\\)? *\\(#?[0-9A-F]+\\|[a-zA-Z0-9\\$\\+.-\\&*_@-]+\\)\\|"
; chl : ajout des champs
	    "[ABCD]=-[ABCD]\\(-1\\)?\\(\\.\\| +\\)\\([0-9ABSWXMP]\\|XS\\|WP\\|1[0-6]\\)\\|"
	    "\\(P=\\)?P[\\+-]1\\|"
	    "\\)\\>"
	    )
	   'font-lock-function-name-face)

     (cons (concat
	    "\\?\\|"
	    "\\*[a-zA-Z0-9.-_\\+\\&@]*"
	    )
	   'font-lock-constant-face)

     (cons (concat
	    "\\<\\(\\(END\\)?CODE\\|\\(LOAD\\)?RPL?\\|"
	   "\\bGOIN[AC2-5]\\|"
	   "G[2-5]\\|"
	   "INCLUDE\\|" "SAVE\\|" "LOADRPL\\|" "LOAD\\|" "RPL\\|" "LOOP\\|" "ERROR_C\\|"
	   "[AC]=IN2\\|" "OUT=C=IN\\|" "RES\\.STR\\|" "RES\\.ROOM\\|" "RESRAM\\|" "SHRINK\\$\\|" "COPY<-\\|" "COPYDN\\|"
	   "COPY->\\|" "COPYUP\\|" "DISPKEY\\|" "DISP\\|"
	   "SRKLST\\|" "SCREEN\\|" "MENU\\|" "ZEROMEM\\|" "MULT\\.A\\|" "MULT\\|" "DIV\\.A\\|" "DIV\\|" "BEEP\\|"
	   "!PATH\\+\\|" "!OFF\\|" "!WAROFF\\|" "!NOCODE\\|" "!DBGON\\|" "!DBCOFF\\|" "!1-16\\|" "!0-15\\|"
	   "!RPL\\|" "!ASM\\|"  "!FL=[01]\\.\\|" "!\\?FL=[01]\\.\\|" "!ABSOLUT\\|" "!ABSADR\\|" "!EVEN\\|" "!ADR\\|" "!COMPEXP\\|"
	   "\\)\\>")
	   'font-lock-type-face)

     ; Extable
     (cons (concat
	    "\\<\\("
"\\~xFROOTS\\|\\~xFXND\\|\\~xGAUSS\\|\\~xGCD\\|\\~xGCDMOD\\|\\~xGROBADD\\|\\~xHADAMARD\\|\\~xHALFTAN\\|\\~xHERMITE\\|\\~xHESS\\|\\~xHILBERT\\|\\~xHORNER\\|\\~xIABCUV\\|\\~xIBP\\|\\~xICHINREM\\|\\~xIDIV2\\|\\~xIEGCD\\|\\~xILAP\\|\\~xINTVX\\|\\~xINVMOD\\|\\~xIQUOT\\|\\~xIREMAINDER\\|\\~xISPRIME\\?\\|\\~xJORDAN\\|\\~xKEYEVAL\\|\\~xLAGRANGE\\|\\~xLAP\\|\\~xLAPL\\|\\~xLCM\\|\\~xLCXM\\|\\~xLDEC\\|\\~xLEGENDRE\\|\\~xLGCD\\|\\~xLIMIT\\|\\~xLIN\\|\\~xLINSOLVE\\|\\~xLNAME\\|\\~xLNCOLLECT\\|\\~xLVAR\\|\\~xMAD\\|\\~xMAIN\\|\\~xMAP\\|\\~xMATR\\|\\~xMENUXY\\|\\~xMODSTO\\|\\~xMULTMOD\\|\\~xNEXTPRIME\\|\\~xPA2B2\\|\\~xPARTFRAC\\|\\~xPCAR\\|\\~xPLOT\\|\\~xPLOTADD\\|\\~xPOWMOD\\|\\~xPREVAL\\|\\~xPREVPRIME\\|\\~xPROMPTSTO\\|\\~xPROPFRAC\\|\\~xPTAYL\\|\\~xQUOT\\|\\~xQXA\\|\\~xREF\\|\\~xREMAINDER\\|\\~xREORDER\\|\\~xRISCH\\|\\~xRREFMOD\\|\\~xSCROLL\\|\\~xSERIES\\|\\~xSEVAL\\|\\~xSIGNTAB\\|\\~xSIMP2\\|\\~xSINCOS\\|\\~xSOLVE\\|\\~xSOLVER\\|\\~xSOLVEVX\\|\\~xSUBST\\|\\~xSUBTMOD\\|\\~xSYLVESTER\\|\\~xTABVAL\\|\\~xTABVAR\\|\\~xTAN2SC\\|\\~xTAN2SC2\\|\\~xTAYLOR0\\|\\~xTCHEBYCHEFF\\|\\~xTCOLLECT\\|\\~xTEVAL\\|\\~xTEXPAND\\|\\~xTLIN\\|\\~xTRAN\\|\\~xTRIG\\|\\~xTRIGCOS\\|\\~xTRIGO\\|\\~xTRIGSIN\\|\\~xTRIGTAN\\|\\~xTRUNC\\|\\~xTSIMP\\|\\~xVANDERMONDE\\|\\~xVER\\|\\~xXNUM\\|\\~xXQ\\|\\~xZEROS\\|\\~x\9F\\|\\~xrref\\|"
"xTVARS\\|xTYPE\\|xUBASE\\|xUFACT\\|xUNPICK\\|xUNROT\\|xUNTIL\\|xUPDIR\\|xUTPC\\|xUTPF\\|xUTPN\\|xUTPT\\|xUVAL\\|xV>\\|xVAR\\|xVARS\\|xVTYPE\\|xWAIT\\|xWHERE\\|xWHILE\\|xWHILEEND\\|xWSLOG\\|xXCOL\\|xXMIT\\|xXOR\\|xXPON\\|xXRNG\\|xXROOT\\|xYCOL\\|xYRNG\\|x\\^\\|xferfailerr\\|xi\\|xnsgeneral\\|xsngeneral\\|xssgeneral\\|{}>DIR\\|{}N\\|~BRRclC1\\|~BRRclCurRow\\|~BRStoC1\\|~BRbrowse\\|~BRoutput\\|~Choose\\|~ChooseMenu0\\|~ChooseMenu1\\|~ChooseMenu2\\|~ChooseSimple\\|~DoMsgBox\\|~IFMenuRow1\\|~IFMenuRow2\\|~INTEMPOB\\?\\|~MESRclEqn\\|~MsgBoxMenu\\|~PCunpack\\|~UTBADATERR\\|~UTTYPEEXT0\\?\\|~UTVUNS1Arg\\|~gFldVal\\|~grobAlertIcon\\|~grobCheckKey\\|~nNullBind\\|~sFldVal\\|~x\\?\\|~xABCUV\\|~xACOS2S\\|~xADDTMOD\\|~xARIT\\|~xASIN2C\\|~xASIN2T\\|~xATAN2S\\|~xAXL\\|~xAXM\\|~xAXQ\\|~xBASE\\|~xCASCFG\\|~xCHINREM\\|~xCMPLX\\|~xCURL\\|~xDERIV\\|~xDERVX\\|~xDESOLVE\\|~xDIFF\\|~xDIV\\|~xDIV2\\|~xDIV2MOD\\|~xDIVIS\\|~xDIVMOD\\|~xDIVPC\\|~xEGCD\\|~xEPSX0\\|~xEULER\\|~xEXLR\\|~xEXP\\&LN\\|~xEXPAND\\|~xEXPANDMOD\\|~xEXPLN\\|~xFACTOR\\|~xFACTORMOD\\|~xFACTORS\\|~xFCOEF\\|~xFOURIER\\|"
"xRCWS\\|xRDM\\|xRDZ\\|xRE\\|xRECN\\|xRECV\\|xREPEAT\\|xREPL\\|xRES\\|xRESTORE\\|xRL\\|xRLB\\|xRND\\|xRNRM\\|xROLL\\|xROLLD\\|xROOT\\|xROT\\|xRPL>\\|xRPN->\\|xRR\\|xRRB\\|xRSD\\|xRULES\\|xSAME\\|xSBRK\\|xSCALE\\|xSCATRPLOT\\|xSCATTER\\|xSCI\\|xSCLSIGMA\\|xSCONJ\\|xSDEV\\|xSEND\\|xSERVER\\|xSETDATE\\|xSETTIME\\|xSF\\|xSHOW\\|xSIGMA\\+\\|xSIGMA-\\|xSIGMACOL\\|xSIGMALINE\\|xSIGN\\|xSILENT'\\|xSIN\\|xSINH\\|xSINV\\|xSIZE\\|xSL\\|xSLB\\|xSNEG\\|xSQ\\|xSQRT\\|xSR\\|xSRB\\|xSRECV\\|xSTART\\|xSTARTVAR\\|xSTD\\|xSTEP\\|xSTEQ\\|xSTIME\\|xSTO\\|xSTO\\*\\|xSTO\\+\\|xSTO-\\|xSTO/\\|xSTO>\\|xSTOALARM\\|xSTOF\\|xSTOKEYS\\|xSTOSIGMA\\|xSTR>\\|xSTRUCT->\\|xSTRUCT>\\|xSTWS\\|xSUB\\|xSUM\\|xSUMX\\|xSUMX2\\|xSUMXY\\|xSUMY\\|xSUMY2\\|xSWAP\\|xSYSEVAL\\|xTAN\\|xTANH\\|xTAYLR\\|xTEXT\\|xTHEN\\|xTHENCASE\\|xTICKS\\|xTIME\\|xTLINE\\|xTMENU\\|xTOT\\|xTRANSIO\\|xTRN\\|xTRNC\\|xTRUTH\\|xTSTR\\|"
"xINV\\|xIP\\|xISOL\\|xKERRM\\|xKEY\\|xKGET\\|xKILL\\|xLABEL\\|xLAST\\|xLCD>\\|xLIBS\\|xLINE\\|xLINFIT\\|xLIST>\\|xLN\\|xLNP1\\|xLOG\\|xLOGFIT\\|xLR\\|xMANT\\|xMATCHDN\\|xMATCHUP\\|xMAX\\|xMAXR\\|xMAXSIGMA\\|xMEAN\\|xMEM\\|xMENU\\|xMERGE\\|xMIN\\|xMINR\\|xMINSIGMA\\|xMOD\\|xNDUPN\\|xNEG\\|xNEGNEG\\|xNEWOB\\|xNEXT\\|xNIP\\|xNOEVAL>\\|xNOT\\|xNOVAL\\|xNSIGMA\\|xNUM\\|xOBJ>\\|xOCT\\|xOFF\\|xOLDPRT\\|xOPENIO\\|xOR\\|xORDER\\|xOVER\\|xPARAMETRIC\\|xPARITY\\|xPATH\\|xPDIM\\|xPERM\\|xPGDIR\\|xPI\\|xPICK\\|xPICK3\\|xPICT\\|xPIX\\?\\|xPIXOFF\\|xPIXON\\|xPKT\\|xPMAX\\|xPMIN\\|xPOLAR\\|xPOS\\|xPR1\\|xPREDIV\\|xPREDV\\|xPREDX\\|xPREDY\\|xPRLCD\\|xPROMPT\\|xPRST\\|xPRSTC\\|xPRVAR\\|xPURGE\\|xPUT\\|xPUTI\\|xPVARS\\|xPVIEW\\|xPWRFIT\\|xPX>C\\|xQUAD\\|xQUOTE\\|xR>B\\|xR>C\\|xR>D\\|xR>I\\|xRAD\\|xRAND\\|xRCEQ\\|xRCL\\|xRCLALARM\\|xRCLF\\|xRCLKEYS\\|xRCLMENU\\|xRCLSIGMA\\|"
"xCONJ\\|xCONSTANTe\\|xCONT\\|xCONVERT\\|xCORR\\|xCOS\\|xCOSH\\|xCOV\\|xCR\\|xCRDIR\\|xCROSS\\|xD>R\\|xDATE\\|xDATE\\+\\|xDDAYS\\|xDEC\\|xDECR\\|xDEFINE\\|xDEG\\|xDELALARM\\|xDELAY\\|xDELKEYS\\|xDEPND\\|xDEPTH\\|xDER\\|xDET\\|xDETACH\\|xDIR\\|xDISP\\|xDO\\|xDOERR\\|xDOT\\|xDRAW\\|xDRAX\\|xDROP\\|xDROP2\\|xDROPN\\|xDTAG\\|xDUP\\|xDUP2\\|xDUPDUP\\|xDUPN\\|xELSE\\|xENDDO\\|xENDTIC\\|xENG\\|xEQ>\\|xERASE\\|xERR0\\|xERRM\\|xERRN\\|xERRTHEN\\|xEVAL\\|xEVAL>\\|xEXP\\|xEXPAN\\|xEXPFIT\\|xEXPM\\|xFACT\\|xFAST3D\\|xFC\\?\\|xFC\\?C\\|xFCNAPPLY\\|xFINDALARM\\|xFINISH\\|xFIX\\|xFLOOR\\|xFORMUNIT\\|xFP\\|xFREE\\|xFREEZE\\|xFS\\?\\|xFS\\?C\\|xFUNCTION\\|xGET\\|xGETI\\|xGOR\\|xGRAD\\|xGRAPH\\|xGROB\\|xGXOR\\|xHALT\\|xHEX\\|xHISTOGRAM\\|xHISTPLOT\\|xHMS\\+\\|xHMS-\\|xHMS>\\|xHOME\\|xI>R\\|xIDN\\|xIF\\|xIFEND\\|xIFERR\\|xIFT\\|xIFTE\\|xIM\\|xINCR\\|xINDEP\\|xINPUT\\|xINT\\|xINTEGRAL\\|"
"top\\&\\|top\\&Cr\\|um\\*\\|um/\\|umEND\\|umP\\|um\\^\\|uncrunch\\|undo\\|unitob\\|unroll2ND\\|w->W\\|x#\\?\\|x%\\|x%CH\\|x%T\\|x'\\|x\\*\\|x\\*H\\|x\\*W\\|x\\+\\|x-\\|x->Q\\|x->QPI\\|x->TAG\\|x/\\|x;\\|x<\\|x<<\\|x<=\\?\\|x<STRUCT\\|x=\\|x==\\|x>\\|x>=\\?\\|x>>\\|x>>ABND\\|x>ARRY\\|x>GROB\\|x>HMS\\|x>LCD\\|x>LIST\\|x>NUM\\|x>STR\\|x>UNIT\\|x>V2\\|x>V3\\|xABS\\|xACK\\|xACKALL\\|xACOS\\|xACOSH\\|xALG->\\|xALOG\\|xAND\\|xANS\\|xAPPLY\\|xARC\\|xARCHIVE\\|xARG\\|xARRY>\\|xASIN\\|xASINH\\|xASN\\|xASR\\|xATAN\\|xATANH\\|xATTACH\\|xAUTO\\|xAXES\\|xB>R\\|xBAR\\|xBARPLOT\\|xBAUD\\|xBEEP\\|xBESTFIT\\|xBIN\\|xBINS\\|xBLANK\\|xBOX\\|xBUFLEN\\|xBYTES\\|xC>PX\\|xC>R\\|xCASE\\|xCEIL\\|xCENTR\\|xCF\\|xCHR\\|xCKSM\\|xCLEAR\\|xCLKADJ\\|xCLLCD\\|xCLOSEIO\\|xCLSIGMA\\|xCLUSR\\|xCMDAPPLY\\|xCNRM\\|xCOLCT\\|xCOMB\\|xCON\\|xCONIC\\|"
"bit#%-\\|bit#%/\\|bit%#*\\|bit%#\\+\\|bit%#-\\|bit%#/\\|bit\\*\\|bit\\+\\|bit-\\|bit/\\|bitAND\\|bitASR\\|bitNOT\\|bitOR\\|bitRL\\|bitRLB\\|bitRR\\|bitRRB\\|bitSL\\|bitSLB\\|bitSR\\|bitSRB\\|bitXOR\\|case\\|case2DROP\\|case2drop\\|case2drpfls\\|caseDEADKEY\\|caseDROP\\|caseDoBadKey\\|caseDrpBadKy\\|caseERRJMP\\|caseFALSE\\|caseSIZEERR\\|caseTRUE\\|casedrop\\|casedrpfls\\|casedrptru\\|cfC\\|cfF\\|char\\|cknumdsptch1\\|clkspd\\|clrtimeout\\|cmp\\|constuniterr\\|convertbase\\|corner\\|dARRYcase\\|dIDNTNcase\\|dLISTcase\\|dREALNcase\\|delimcase\\|derprod1\\|derquot\\|docr\\|dostws\\|dowait\\|dowutil\\|drax\\|dvarlsBIND\\|easyabs\\|ederr\\|editdecomp\\$w\\|failed\\|get1\\|getBPOFF\\|getmatchtok\\|getxpos\\|getypos\\|grob\\|hxs\\|hxs>\\$\\|id\\|idnt\\|idntcase\\|idntlamcase\\|infreserr\\|intrptderr\\|j%0=case\\|jEQcase\\|kermpktmsg\\|kermrecvmsg\\|kermsendmsg\\|laMGET0\\|lam\\|list\\|liteslp\\|lowbaterr\\|makebeep\\|makegrob\\|matchob\\?\\|matchob\\?Lp\\|metaROTDUP\\|metatail\\|mpop1%\\|nCOLCTQUOTE\\|nCustomMenu\\|nDISPSTACK\\|nWHEREDER\\|nWHEREIFTE\\|nWHEREINTG\\|"
"\\^xSYMR>D\\|\\^xSYMRE\\|\\^xSYMSIGN\\|\\^xSYMSIN\\|\\^xSYMSINH\\|\\^xSYMSQ\\|\\^xSYMSQRT\\|\\^xSYMTAN\\|\\^xSYMTANH\\|\\^xSYMXPON\\|\\^xTANHext\\|\\^xTANext\\|\\^x\\^ext\\|\\^xroot2expln\\|\\^xssSYM#\\?\\|\\^xssSYM%\\|\\^xssSYM%CH\\|\\^xssSYM%T\\|\\^xssSYM\\*\\|\\^xssSYM\\+\\|\\^xssSYM-\\|\\^xssSYM/\\|\\^xssSYM<=\\?\\|\\^xssSYM<\\?\\|\\^xssSYM=\\?\\|\\^xssSYM>=\\?\\|\\^xssSYM>\\?\\|\\^xssSYMAND\\|\\^xssSYMCOMB\\|\\^xssSYMMAX\\|\\^xssSYMMIN\\|\\^xssSYMMOD\\|\\^xssSYMOR\\|\\^xssSYMPERM\\|\\^xssSYMRNDXY\\|\\^xssSYMTRCXY\\|\\^xssSYMXOR\\|\\^xssSYMXROOT\\|\\^xssSYM\\^\\|\\^xvext\\|\\^zsigne\\|\\^{}POLY\\|\\^{}TO\\[\\]\\|a%>\\$\\|a%>\\$,\\|aBZU\\|aCircleB\\|aCircleG1\\|aCircleG2\\|aCircleW\\|aCircleXor\\|aDistance\\|aFBoxB\\|aFBoxG1\\|aFBoxG2\\|aFBoxW\\|aFBoxXor\\|aGNeg\\|aGrey\\?\\|aH>HMS\\|aLBoxB\\|aLBoxG1\\|aLBoxG2\\|aLBoxW\\|aLBoxXor\\|aLineB\\|aLineG1\\|aLineG2\\|aLineW\\|aLineXor\\|aMODF\\|aPixonB\\|aPixonG1\\|aPixonG2\\|aPixonW\\|aPixonXor\\|aScroolVGrob\\|aSubReplGor\\|aSubReplGxor\\|aSubReplRepl\\|addrADISP\\|addrATTNFLG\\|addrClkOnNib\\|addrKEYSTATE\\|addrLINECNTg\\|addrORghost\\|addrTEMPENV\\|addrTEMPTOP\\|addrVDISP\\|addrVDISP2\\|addtics\\|adrDISABLE_K\\|adrKEYBUFFER\\|adrTIMEOUTCLK\\|allkeys\\|any\\|apndvarlst\\|argtypeerr\\|argvalerr\\|arry\\|bit#%\\*\\|bit#%\\+\\|"
"\\^metaneg\\|\\^metapi\\|\\^metapi\\*2\\|\\^metapi/2\\|\\^metapi/4\\|\\^metapi\\?\\|\\^metapow\\|\\^metareal\\?\\|\\^metasimp\\|\\^metasplit\\|\\^metasq\\+1\\|\\^metasq-1\\|\\^metasub\\|\\^metaundef\\|\\^metaxroot\\|\\^minusinf\\|\\^n{}N\\|\\^pi\\|\\^pi/2-acos\\|\\^pi/2-asin\\|\\^pi/2-meta\\|\\^pifois2\\|\\^pisur-2\\|\\^pisur2\\|\\^plusinf\\|\\^prepvarlist\\|\\^pshder\\*\\|\\^risch/\\|\\^rischABS\\|\\^rischlogpart\\|\\^rpnQOBJext\\|\\^rref\\|\\^siSYMDER\\|\\^sin/cos\\|\\^sin2exp\\|\\^sin2tan\\|\\^sin2tan/2\\|\\^sinh2exp\\|\\^sqrt1-cos\\^2\\|\\^sqrt1-sin\\^2\\|\\^sqrt2lnexp\\|\\^ssSYMDER\\|\\^submeta\\|\\^sympsi\\|\\^sympsin\\|\\^tan2exp\\|\\^tan2tan/2\\|\\^tanh2exp\\|\\^top&addt\\*\\|\\^top&addt/\\|\\^unsignedinf\\|\\^vgerxssSYMSUM\\|\\^x\\*ext\\|\\^x\\+ext\\|\\^x-ext\\|\\^x/ext\\|\\^x=ext\\|\\^xABSext\\|\\^xACOSHext\\|\\^xACOSext\\|\\^xASINHext\\|\\^xASINext\\|\\^xATANHext\\|\\^xATANext\\|\\^xCOSHext\\|\\^xCOSext\\|\\^xEXPext\\|\\^xIMext\\|\\^xINVext\\|\\^xLNext\\|\\^xREext\\|\\^xSINHext\\|\\^xSINext\\|\\^xSQext\\|\\^xSYMABS\\|\\^xSYMACOS\\|\\^xSYMACOSH\\|\\^xSYMALOG\\|\\^xSYMARG\\|\\^xSYMASIN\\|\\^xSYMASINH\\|\\^xSYMATAN\\|\\^xSYMATANH\\|\\^xSYMCEIL\\|\\^xSYMCHS\\|\\^xSYMCONJ\\|\\^xSYMCOS\\|\\^xSYMCOSH\\|\\^xSYMD>R\\|\\^xSYMEXP\\|\\^xSYMEXPM1\\|\\^xSYMFACT\\|\\^xSYMFLOOR\\|\\^xSYMFP\\|\\^xSYMIM\\|\\^xSYMINV\\|\\^xSYMIP\\|\\^xSYMLN\\|\\^xSYMLNP1\\|\\^xSYMLOG\\|\\^xSYMMANT\\|\\^xSYMNOT\\|"
"\\^addtAND\\|\\^addtARG\\|\\^addtASIN\\|\\^addtASINH\\|\\^addtATAN\\|\\^addtATANH\\|\\^addtCEIL\\|\\^addtCOMB\\|\\^addtCONJ\\|\\^addtCOS\\|\\^addtCOSH\\|\\^addtD->R\\|\\^addtEXP\\|\\^addtEXPM\\|\\^addtFACT\\|\\^addtFLOOR\\|\\^addtFP\\|\\^addtINV\\|\\^addtIP\\|\\^addtLN\\|\\^addtLNP1\\|\\^addtLOG\\|\\^addtMANT\\|\\^addtMAX\\|\\^addtMIN\\|\\^addtMOD\\|\\^addtNOT\\|\\^addtOR\\|\\^addtPERM\\|\\^addtR->D\\|\\^addtRND\\|\\^addtSIGN\\|\\^addtSIN\\|\\^addtSINACOS\\|\\^addtSINH\\|\\^addtSQ\\|\\^addtSQRT\\|\\^addtTAN\\|\\^addtTAN/2\\|\\^addtTANH\\|\\^addtTRNC\\|\\^addtXOR\\|\\^addtXPON\\|\\^addtXROOT\\|\\^addt\\^\\|\\^addti\\|\\^algparse\\|\\^algunwrap\\|\\^asin2atan\\|\\^asin2ln\\|\\^asinh2ln\\|\\^atan2asin\\|\\^atan2ln\\|\\^atanh2ln\\|\\^base_ln\\|\\^ckaddt\\*\\|\\^ckaddt\\+\\|\\^ckaddt-\\|\\^cos\\*tan\\|\\^cos2exp\\|\\^cos2tan\\|\\^cos2tan/2\\|\\^cosh2exp\\|\\^deuxipi\\|\\^exp2sincos\\|\\^factorial\\|\\^facts\\|\\^factzint\\|\\^fk\\+1/fk\\|\\^insertrow\\[\\]\\|\\^ipi\\|\\^la\\+ELEMsym\\|\\^laDELROW\\|\\^laGPROW\\|\\^laINSROW\\|\\^linearapply\\|\\^m-1\\&m\\+1\\|\\^make2dmatrix\\|\\^mattran\\|\\^mattrn\\|\\^meta-1\\|\\^meta-pi\\|\\^meta-pi/2\\|\\^meta-pi/4\\|\\^meta/2\\|\\^meta1-sq\\|\\^meta1/meta\\|\\^meta2\\*\\|\\^metaCOMPARE\\|\\^metaEQUAL\\?\\|\\^meta\\^\\|\\^meta_cst\\?\\|\\^meta_e\\|\\^metaadd\\|\\^metackneg\\|\\^metadiv\\|\\^metafraction\\?\\|\\^metai\\|\\^metai\\*\\|\\^metainftype\\|\\^metaipi\\|\\^metamult\\|"
"\\^VARCOMP2!\\|\\^VARCOMP3!\\|\\^VARCOMP31!\\|\\^VARCOMP32!\\|\\^VARCOMP33!\\|\\^VARCOMPLN!\\|\\^VARGENext\\|\\^VBINARYOP\\|\\^VERBOSEMODE\\|\\^VERNUMext\\|\\^VPMULT\\|\\^VRRDM\\|\\^VRRDMmeta\\|\\^VSUB\\|\\^VUNARYOP\\|\\^VX!\\|\\^VX>\\|\\^VX>LVARext\\|\\^VXINDEP\\?\\|\\^VXINDEPERR\\|\\^VXLVARext\\|\\^VXXL0\\|\\^VXXL1ext\\|\\^VXXL2\\|\\^VXXL2NR\\|\\^VXXLFext\\|\\^VXXLext\\|\\^VarFactor\\|\\^Verbose1\\|\\^Verbose2\\|\\^Verbose3\\|\\^VerboseN\\|\\^WARNSING\\|\\^WRITEMENU\\|\\^XEQ>ARRAY1\\|\\^XEQ>ARRY\\|\\^XEQARRY>\\|\\^XGROBext\\|\\^XNUM\\|\\^XROOT2ext\\|\\^XROOT_IN\\?\\|\\^XSQRext\\|\\^XYext\\|\\^Z2%%\\|\\^Z2BIN\\|\\^Z2Sext\\|\\^Z<0ERR\\|\\^Z>#\\|\\^Z>#ERR\\|\\^Z>R\\|\\^Z>S\\|\\^Z>ZH\\|\\^ZABS\\|\\^ZAbs\\|\\^ZBit\\?\\|\\^ZBits\\|\\^ZDIVext\\|\\^ZEILBERGER\\|\\^ZEROS1EQ\\|\\^ZEROSMANYEQ\\|\\^ZFACTO\\|\\^ZFactor\\|\\^ZGCDext\\|\\^ZGcd\\|\\^ZINTSQRT\\|\\^ZIsNeg\\?\\|\\^ZIsOne\\?\\|\\^ZIsPrime\\?\\|\\^ZMod\\|\\^ZNLT\\?\\|\\^ZNMax\\|\\^ZNMin\\|\\^ZPrime\\?\\|\\^ZQUOText\\|\\^ZSIGNE\\|\\^ZSIGNECK\\|\\^ZSQRT\\|\\^ZTrialDiv\\|\\^ZTrialDiv2\\|\\^ZTrialPrime\\?\\|\\^ZTrim\\|\\^ZZ2C%%ext\\|\\^\\[\\]TO{}\\|\\^acos2ln\\|\\^acosh2ln\\|\\^addt!=\\|\\^addt%\\|\\^addt%CH\\|\\^addt%T\\|\\^addt/\\|\\^addt0meta\\|\\^addt2\\|\\^addt<\\|\\^addt<=\\|\\^addt==\\|\\^addt>\\|\\^addt>=\\|\\^addtABS\\|\\^addtABSEXACT\\|\\^addtACOS\\|\\^addtACOSH\\|\\^addtALOG\\|"
"\\^STOMAText\\|\\^STOMODULO\\|\\^STOPRIMIT\\|\\^STOSYSText\\|\\^STOVX\\|\\^STRICTmetaCOMPARE\\|\\^STUDDIV\\|\\^STUDMULT\\|\\^SUBSIGNE\\|\\^SUBTMOD\\|\\^SUM\\|\\^SUMSQRext\\|\\^SUMVX\\|\\^SUnivar\\?\\|\\^SWAPFXND\\|\\^SWAPNDXF\\|\\^SWAPRADD\\|\\^SWAPRDIV\\|\\^SWAPRIM\\|\\^SWAPRMULT\\|\\^SWAPRNEG\\|\\^SWAPROWS\\|\\^SWAPRRE\\|\\^SWAPRSUB\\|\\^SWITCHNOTALLOWED\\|\\^SWITCHOFF\\|\\^SWITCHON\\|\\^SWPSIMPNDXF\\|\\^SXSQRext\\|\\^SYLVESTER\\|\\^SYMBEXEC\\|\\^SYMBINCOMP\\|\\^SYMBWHERE\\|\\^SYMCOLCT\\|\\^SYMDER\\|\\^SYMEXPAN\\|\\^SYMINTEGRAL\\|\\^SYMISOL\\|\\^SYMLIMIT\\|\\^SYMPAPRX\\|\\^SYMPSI\\|\\^SYMPSIN\\|\\^SYMQFORM\\|\\^SYMTAYLOR\\|\\^SYSTEM\\|\\^SYSText\\|\\^SortList\\|\\^Sys1IT\\|\\^TABLECOSext\\|\\^TABLETANext\\|\\^TABVALext\\|\\^TABVAR\\|\\^TAN2CS2\\|\\^TAN2EXP\\|\\^TAN2SC\\|\\^TAN2SC2\\|\\^TAN2SC2ext\\|\\^TAN2SCext\\|^\\TAN2TAN/2\\|\\^TANH2EXPext\\|\\^TAYLOR0\\|\\^TCHEBNOCK\\|\\^TCHEBext\\|\\^TCOLLECT\\|\\^TESTINFINI\\|\\^TEXPAext\\|\\^THREE{}POLY\\|\\^TOLISText\\|\\^TRANSCERROR\\|\\^TRCARRY\\|\\^TRIGTAN\\|\\^TRIGext\\|\\^TRIMOBJext\\|\\^TRIMext\\|\\^TRUNCDL\\|\\^TSIMP2ext\\|\\^TSIMP3ext\\|\\^TSIMPext\\|\\^TWO::POLY\\|\\^TWO{}POLY\\|\\^TYPEGAUSSINT\\?\\|\\^TYPEIDNTLAM\\?\\|\\^TYPEIRRQ\\?\\|\\^TYPEREALZINT\\?\\|\\^TYPEZ\\?\\|\\^UFactor\\|\\^UFactor1\\|\\^UFactorDeg2\\|\\^USERFCN\\?\\|\\^USERLIDNT\\|\\^USERLVAR\\|\\^Univar\\?\\|\\^VADD\\|\\^VAL1\\|\\^VAL1M\\|\\^VAL2ext\\|\\^VALMUSTBE0\\|\\^VALOBJext\\|\\^VANDERMONDE\\|\\^VAR%\\|\\^VAR=LIST\\|\\^VARCOMP!\\|"
"\\^RREext\\|\\^RSUBext\\|\\^RmCombNext\\|\\^RunChooseSimple\\|\\^RunDoNewMatrix\\|\\^RunDoOldMatrix\\|\\^S>Z\\|\\^S>Z\\?\\|\\^SAFEPURGE\\|\\^SAMEMATRIX\\|\\^SAMEMATSCTYPE\\|\\^SAVECASFLAGS\\|\\^SC\\*MATMOD\\|\\^SCL\\*MAT\\|\\^SCROLLext\\|\\^SECO2CMPCART\\|\\^SECO2CMPPOL\\|\\^SECO2CMPext\\|\\^SECOEXEC\\|\\^SECOSQFFext\\|\\^SERIESEXPLN\\|\\^SETCOMPLEX\\|\\^SETEXACT\\|\\^SETPLUSAT0\\|\\^SFactor\\|\\^SHALT\\|\\^SHRINK2ASYM\\|\\^SHRINK2SYM\\|\\^SHRINKASYM\\|\\^SHRINKEVEN\\|\\^SHRINKSYM\\|\\^SIGMAEXP2ext\\|\\^SIGMAEXPext\\|\\^SIGNE\\|\\^SIGNE1ext\\|\\^SIGNE>\\|\\^SIGNEATAN\\|\\^SIGNECOS\\|\\^SIGNEERROR\\|\\^SIGNEEXP\\|\\^SIGNELEFT\\|\\^SIGNELN\\|\\^SIGNERIGHT\\|\\^SIGNESIN\\|\\^SIGNESQRT\\|\\^SIGNETAN\\|\\^SIGNEext\\|\\^SIGNMOINS\\|\\^SIGNMULText\\|\\^SIGNPLUS\\|\\^SIGNUNDEF\\|\\^SILENTMODE\\|\\^SIMP1!\\|\\^SIMP1ext\\|\\^SIMP3LISText\\|\\^SIMP3LSTSLOW\\|\\^SIMP3ext\\|\\^SIMPEXTOK\\|\\^SIMPGCDext\\|\\^SIMPIDNT\\|\\^SIMPLIFY\\|\\^SIMPNDXFext\\|\\^SIMPSYMBS\\|\\^SIMPUSERFCN\\|\\^SIMPVAR\\|\\^SIMPext\\|\\^SIMP|\\|\\^SIN2EXPext\\|\\^SIN2TAN\\|\\^SIN2TAN/2\\|\\^SIN2TC\\|\\^SIN2TCext\\|\\^SIN2ext\\|\\^SINCOSext\\|\\^SINEXPA\\|\\^SINEXPA\\*\\|\\^SINEXPA\\*1\\|\\^SINEXPA\\+\\|\\^SINEXPA-\\|\\^SINH2EXPext\\|\\^SINTEST\\|\\^SIsPrime\\?\\|\\^SLOPPY\\?\\|\\^SLOPPYMODE\\|\\^SLOWGCDext\\|\\^SLOWSIMP2L\\|\\^SLVARext\\|\\^SOLVE1EQ\\|\\^SOLVECRAMER\\|\\^SOLVEMANYEQ\\|\\^SOLVEMETASYST\\|\\^SOLVEXFLOAT\\|\\^SOLVext\\|\\^SPARSEDATA\\|\\^SPollard\\|\\^SQFF2ext\\|\\^SQFFext\\|\\^SQRT2LNEXP\\|\\^SQRTINVpshd\\*\\|\\^SQRT_IN\\?\\|\\^STEPBYSTEP\\|\\^STEPIDIV2\\|"
"\\^PSQFF\\|\\^PSetSign\\|\\^PSqff\\|\\^PTAYLext\\|\\^PTrim\\|\\^PULLEL\\[S\\]\\|\\^PUT\\[\\]\\|\\^PZHSTR\\|\\^PZadic\\|\\^Prime\\+\\|\\^Prime\\-\\|\\^QABSext\\|\\^QAdd\\|\\^QAddMod\\|\\^QCONJext\\|\\^QDiv\\|\\^QDiv\\?\\|\\^QDivMod\\|\\^QDivRem\\|\\^QGcd\\|\\^QGcdExMod\\|\\^QGcdMod\\|\\^QInvMod\\|\\^QIsZero\\?\\|\\^QMODSYMext\\|\\^QMod\\|\\^QMul\\|\\^QMulMod\\|\\^QNORMext\\|\\^QNeg\\|\\^QPI\\|\\^QRoot\\|\\^QSub\\|\\^QSubMod\\|\\^QUADRANT\\|\\^QUOTExSIGMA\\|\\^QUOTOBJext\\|\\^QUOText\\|\\^QXA\\|\\^QXNDext\\|\\^Qpi\\|\\^Qpi%\\|\\^QpiArry\\|\\^QpiList\\|\\^QpiSym\\|\\^QpiZ\\|\\^R15SIMP\\|\\^R2SYM\\|\\^R2Zext\\|\\^R>Z\\|\\^RABSext\\|\\^RACTOFACext\\|\\^RADDext\\|\\^RASOP\\|\\^RATSUM\\|\\^RCL1IDNT\\|\\^RCLALLIDNT\\|\\^RCLEPS\\|\\^RCLMODULO\\|\\^RCLPERIOD\\|\\^RCLVX\\|\\^RCONJext\\|\\^RDIVext\\|\\^REAL\\?\\|\\^REALBICAR\\|\\^REALLN\\|\\^REALMODE\\|\\^RECURMODE\\|\\^REDUCE\\|\\^REDUCEMETAPSYST\\|\\^REDUCEMETASYST\\|\\^REGCDext\\|\\^RENAME\\|\\^REORDER\\|\\^REPLACE2BY1\\|\\^RESETCASCFG\\|\\^RESPSHIFTQ\\|\\^RESTORECASFLAGS\\|\\^RESULTANT\\|\\^RESULTANTLP\\|\\^REWRITEIFINF\\|\\^RFACT2ext\\|\\^RFACTSTEP3\\|\\^RFACTSTEP5\\|\\^RFACText\\|\\^RIGORMODE\\|\\^RIMext\\|\\^RISCH13\\|\\^RISCHPF\\|\\^RISCHRAT\\|\\^RISCHext\\|\\^RIXCext\\|\\^RLVARext\\|\\^RMULText\\|\\^RNDARRY\\|\\^RNEGext\\|\\^ROOTM2ROOT\\|\\^ROOT{}N\\|\\^RP#\\|\\^RPext\\|\\^RRDMext\\|\\^RREFMOD\\|"
"\\^MetaPow\\|\\^MetaSub\\|\\^Mod\\|\\^ModAdd\\|\\^ModDiv\\|\\^ModDiv2\\|\\^ModExpa\\|\\^ModFctr\\|\\^ModGcd\\|\\^ModInv\\|\\^ModLGCD\\|\\^ModLOPD\\|\\^ModMul\\|\\^ModPow\\|\\^ModSub\\|\\^MonicLf\\|\\^NDEvalN/D\\|\\^NDROPZ0\\|\\^NDROPZ1\\|\\^NDROPZERO\\|\\^NDROPminusinf\\|\\^NDROPplusinf\\|\\^NDXFext\\|\\^NDXQext\\|\\^NEWDIVext\\|\\^NEWLIMHORN\\|\\^NEWMODULO\\|\\^NEWTRIMext\\|\\^NEWVX\\|\\^NEXTPext\\|\\^NFactor\\|\\^NFactorSpc\\|\\^NONALGERR\\|\\^NONINTERR\\|\\^NONPOLYSYST\\|\\^NONRATSUM\\|\\^NONRECMODE\\|\\^NONUNARYERR\\|\\^NOSTEPBYSTEP\\|\\^NR_REPLACE\\|\\^NULLVECTOR\\?\\|\\^NUMMODE\\|\\^OBJ2REAL\\|\\^OBJDIMS2MAT\\|\\^OBJINT\\?\\|\\^OBJPOSINT\\?\\|\\^ODETYPESTO\\|\\^ODE_INT\\|\\^ODE_SEPAR\\|\\^ONE>POLY\\|\\^ONE{}POLY\\|\\^P2P#\\|\\^PA2B2\\|\\^PARITYTEST\\|\\^PARTFRAC\\|\\^PARTFRACRAT\\|\\^PASCAL_NEXTLINE\\|\\^PCAR\\|\\^PDIV2ext\\|\\^PDer\\|\\^PDivLk\\|\\^PEGCD\\|\\^PEVAL\\|\\^PEval\\|\\^PEvalFast\\?\\|\\^PEvalMod\\|\\^PEvalN/D\\|\\^PFEXECext\\|\\^PFactPowCnt\\|\\^PFactTriv\\|\\^PFactor\\|\\^PFext\\|\\^PHFctr\\|\\^PHFctr0\\|\\^PHFctr1\\|\\^PIVOTFLOAT\\|\\^PIVOTNORM\\|\\^PIext\\|\\^PLCZ\\|\\^PLOTADD\\|\\^PLOTSTK\\|\\^PLUSAT0\\|\\^PLUSATINFTY\\|\\^PLUSINFext\\|\\^PNFctr\\|\\^PNMax\\|\\^POLYASYM\\|\\^POLYPARITY\\|\\^POLYSYM\\|\\^POSINFext\\|\\^POSITIFext\\|\\^POSUNDEFext\\|\\^POTENCEext\\|\\^PPP\\|\\^PPZ\\|\\^PPZZ\\|\\^PPow#\\|\\^PREPARext\\|\\^PREVALext\\|\\^PROMPTSTO1\\|\\^PSEUDODIV\\|\\^PSEUDOPREP\\|"
"\\^MENUCHOOSE\\?\\|\\^MENUCMPLX1\\|\\^MENUDIFF1\\|\\^MENUEXPLN1\\|\\^MENUGENE1\\|\\^MENUMAT1\\|\\^MENUSOLVE1\\|\\^MENUTRIG1\\|\\^MENUXYext\\|\\^MENUext\\|\\^METACOMP0\\|\\^METACOMP1\\|\\^METACOMPRIM\\|\\^METACOSEXPA\\|\\^METADEG1\\|\\^METADEG2\\|\\^METADENOLCM\\|\\^METADER\\&NEG\\|\\^METADER\\*\\|\\^METADER\\+\\|\\^METADER-\\|\\^METADER/\\|\\^METADERABS\\|\\^METADERACH\\|\\^METADERACOS\\|\\^METADERALOG\\|\\^METADERASH\\|\\^METADERASIN\\|\\^METADERATAN\\|\\^METADERATH\\|\\^METADERCOS\\|\\^METADERCOSH\\|\\^METADERDER\\|\\^METADEREXP\\|\\^METADERFCN\\|\\^METADERI3\\|\\^METADERI4\\|\\^METADERIFTE\\|\\^METADERINV\\|\\^METADERIV\\|\\^METADERLN\\|\\^METADERLNP1\\|\\^METADERLOG\\|\\^METADERNEG\\|\\^METADEROP\\|\\^METADERSIN\\|\\^METADERSINH\\|\\^METADERSQ\\|\\^METADERSQRT\\|\\^METADERTAN\\|\\^METADERTANH\\|\\^METADER^\\|\\^METAEXPEXPA\\|\\^METAINT\\?\\|\\^METALISTVXXL\\|\\^METALNEXPA\\|\\^METAMAT-ROW\\|\\^METAMATCSWAP\\|\\^METAMATRED\\|\\^METAMATRSWAP\\|\\^METAMM2\\|\\^METAMULMULT\\|\\^METAPIVOT\\|\\^METAPOSINT\\?\\|\\^METASINEXPA\\|\\^METASOLV\\|\\^METASOLV2\\|\\^METASOLV4\\|\\^METASOLVOUT\\|\\^METASQFFext\\|\\^METATANEXPA\\|\\^METAVAL2\\|\\^MEVALext\\|\\^MFACTORMOD\\|\\^MFactTriv\\|\\^MHORNER\\|\\^MHORNER1\\|\\^MHORNext\\|\\^MINUSINFext\\|\\^MINVMOD\\|\\^MKPOLY\\|\\^MLISTSQFF\\|\\^MMMULT\\|\\^MODULOMAText\\|\\^MODULOMODext\\|\\^MP0\\|\\^MPEXEC\\|\\^MPext\\|\\^MSECOSQFF\\|\\^MSQFF\\|\\^MSUB\\|\\^MSUBTMOD\\|\\^MTRIG2SYMB\\|\\^MULMULText\\|\\^MULTMOD\\|\\^MVMULT\\|\\^MZSQFF\\|\\^MZSQFF1\\|\\^MetaAdd\\|\\^MetaDiv\\|\\^MetaMul\\|\\^MetaNeg\\|"
"\\^LIST1i-1-i\\|\\^LIST2MATRIX\\|\\^LISTEXEC\\|\\^LISTEXEC1\\|\\^LISTIRRQ\\|\\^LISTMAXext\\|\\^LISTOPRAC\\|\\^LISTOPSQRT\\|\\^LISTOPext\\|\\^LISTSECOext\\|\\^LLVARDext\\|\\^LN2ATAN\\|\\^LN2ext\\|\\^LNATANext\\|\\^LNCOLCext\\|\\^LNEXPA\\|\\^LNEXPA*\\|\\^LNEXPA/\\|\\^LNEXPA\\^\\|\\^LNOBJ!\\|\\^LNP12LN\\|\\^LOG2LN\\|\\^LOP1ext\\|\\^LOPAext\\|\\^LOPDext\\|\\^LOPMext\\|\\^LPGCDext\\|\\^LPROF!\\|\\^LRDM!\\|\\^LRDMext\\|\\^LVARDext\\|\\^LVARXNX2!\\|\\^LVARXNX2ext\\|\\^LVARXNXext\\|\\^LVARext\\|\\^LiftGeneral\\|\\^LiftLinear\\|\\^LiftZAdic\\|\\^ListPos\\|\\^ListToArry\\|\\^MADD\\|\\^MADDTMOD\\|\\^MADJ\\|\\^MADNOCK\\|\\^MAKE2DMATRIX\\|\\^MAKEARRY\\|\\^MAKEPROFOND\\|\\^MAKESYSText\\|\\^MAT\\*\\|\\^MAT\\*MATMOD\\|\\^MAT\\*SCL\\|\\^MAT\\*SCMOD\\|\\^MAT\\+\\|\\^MAT-\\|\\^MAT/\\|\\^MAT/SCL\\|\\^MATCHS\\|\\^MATCNORM\\|\\^MATCON\\|\\^MATCONJ\\|\\^MATCROSS\\|\\^MATDET\\|\\^MATDOT\\|\\^MATEGV\\|\\^MATEGVL\\|\\^MATEXPLODE\\|\\^MATFNORM\\|\\^MATIDN\\|\\^MATIM\\|\\^MATINV\\|\\^MATRANK\\|\\^MATRANM\\|\\^MATRDET\\|\\^MATRE\\|\\^MATREDIM\\|\\^MATREF\\|\\^MATREFRREF\\|\\^MATREPL\\|\\^MATRIX-COL\\|\\^MATRIX-ROW\\|\\^MATRIX2ARRAY\\|\\^MATRIX2LIST\\|\\^MATRIX>DIAG\\|\\^MATRIXCSWAP\\|\\^MATRIXDIAG>\\|\\^MATRIXDIM\\|\\^MATRIXRCI\\|\\^MATRIXRCIJ\\|\\^MATRIXRISCH\\|\\^MATRIXRSWAP\\|\\^MATRNORM\\|\\^MATRREF\\|\\^MATSQUARE\\|\\^MATSUB\\|\\^MATTRACE\\|\\^MATTRAN\\|\\^MATTRN\\|\\^MAT\\^\\|\\^MDIMS\\|\\^MENUARIT1\\|\\^MENUBASE1\\|\\^MENUCHOOSE\\|"
"\\^IfSetCurrentFieldValue\\|\\^IfSetField\\|\\^IfSetFieldPos\\|\\^IfSetFieldResetValue\\|\\^IfSetFieldValue\\|\\^IfSetFieldVisible\\|\\^IfSetGrob\\|\\^IfSetGrob3\\|\\^IfSetHelpString\\|\\^IfSetSelected\\|\\^IfSetTitle\\|\\^IfSetTitle2\\|\\^IfTet\\|\\^IsUncompressDataString\\|\\^IsV>V\\?\\|\\^JORDAN\\|\\^KEYEVAL\\|\\^KeyLookup\\|\\^LAGRANGE\\|\\^LAGRANGEext\\|\\^LAPLACIAN\\|\\^LAPext\\|\\^LASTCOMP\\|\\^LCPROG2M\\|\\^LDECSOLV\\|\\^LDEGENE\\|\\^LDEPART\\|\\^LDSSOLVext\\|\\^LEDispItem\\|\\^LEDispList\\|\\^LEDispPrompt\\|\\^LEGENDRE\\|\\^LENMATRIX\\|\\^LESSCOMPLEX\\?\\|\\^LFCProd\\|\\^LIDNTLVAR\\|\\^LIDNText\\|\\^LIFCext\\|\\^LIM#VARX!\\|\\^LIM%#!\\|\\^LIM\\*!\\|\\^LIM\\+-!\\|\\^LIM/!\\|\\^LIMABS!\\|\\^LIMALPHA!\\|\\^LIMASIN!\\|\\^LIMATAN!\\|\\^LIMATAS!\\|\\^LIMBETA!\\|\\^LIMCMPL!\\|\\^LIMCOMP!\\|\\^LIMDIVPC!\\|\\^LIMDL!\\|\\^LIMDLINF!\\|\\^LIMEQU!\\|\\^LIMEQU0!\\|\\^LIMEQUFR!\\|\\^LIMERR0!\\|\\^LIMERR1!\\|\\^LIMERR10!\\|\\^LIMERR6!\\|\\^LIMEXP!\\|\\^LIMFLOOR!\\|\\^LIMHORN!\\|\\^LIMINFSIGN!\\|\\^LIMINV!\\|\\^LIMINVLN!\\|\\^LIMIT!\\|\\^LIMITNOVX!\\|\\^LIMITX!\\|\\^LIMIText\\|\\^LIMLIM!\\|\\^LIMLIM1!\\|\\^LIMLN!\\|\\^LIMMAX!\\|\\^LIMNEG!\\|\\^LIMPOW!\\|\\^LIMPROF!\\|\\^LIMPROF0!\\|\\^LIMPROF1!\\|\\^LIMPROF2!\\|\\^LIMPROFEND!\\|\\^LIMRAC!\\|\\^LIMSC0!\\|\\^LIMSC1!\\|\\^LIMSERIES!\\|\\^LIMSINCOS!\\|\\^LIMSORT!\\|\\^LIMSQ!\\|\\^LIMSQRT!\\|\\^LIMSTEP1!\\|\\^LIMSTEP2!\\|\\^LIMSTEP3!\\|\\^LIMSTEP4!\\|\\^LIMVAL!\\|\\^LIMVALOBJ!\\|\\^LIMVAR!\\|\\^LINEARAPPLY\\|\\^LINEXPA\\|\\^LINEXPext\\|\\^LINSOLV\\|\\^LIST10-10\\|"
"\\^GROBADDext\\|\\^GSOLVE\\|\\^GetFieldVals\\|\\^GetRoot\\|\\^H>Z\\|\\^HALFTAN\\|\\^HERMITE\\|\\^HESSIAN\\|\\^HILBERTNOCK\\|\\\\^HORN1\\|\\^HORNASIN!\\|\\^HORNASIN1!\\|\\^HORNATAN!\\|\\^HORNCOS!\\|\\^HORNER1ext\\|\\^HORNEXP!\\|\\^HORNLN!\\|\\^HORNSIN!\\|\\^HORNext\\|\\^HSECO2RCext\\|\\^HYP2EXPext\\|\\^HYPERGEO\\|\\^IABCUV\\|\\^IBERNOULLI\\|\\^IBP\\|\\^ICHINREM\\|\\^ID>DERext\\|\\^IDIV2\\|\\^IDNTEXEC\\|\\^IDNTLAM\\?\\|\\^IEGCD\\|\\^IEGCDext\\|\\^IFEDispField\\|\\^ILAPDELTA\\|\\^ILAPEXP\\|\\^ILAPEXPSC\\|\\^ILAPRAText\\|\\^ILAPext\\|\\^INEGCD\\|\\^INFINIext\\|\\^INPARTFRAC\\|\\^INSERTCOL\\[\\]\\|\\^INSERTROW\\[\\]\\|\\^INSERT\\[\\]COL\\[\\]\\|\\^INSERT\\[\\]ROW\\[\\]\\|\\^INSERT{}N\\|\\^INT3\\|\\^INTEGRext\\|\\^INTERNALARG2\\|\\^INTERNALERR\\|\\^INTVARERR\\|\\^INText\\|\\^INVAL2\\|\\^INVALIDOP\\|\\^INVMOD\\|\\^INXREDext\\|\\^IROOTS\\|\\^IRRQ#ULTIMATE\\|\\^IRXC2\\|\\^IRXCext\\|\\^ISIDREAL\\?\\|\\^ISNT_IDNT\\?\\|\\^ISOL1\\|\\^ISOL2ext\\|\\^ISOLALL\\|\\^ISOLERR\\|\\^ISPOLYNOMIAL\\?\\|\\^ISPRIME\\|\\^IS_SQRT\\?\\|\\^IS_XROOT\\?\\|\\^IfCheckFieldtype\\|\\^IfCheckSetValue\\|\\^IfCreateTitleGrob\\|\\^IfDisplayFromData\\|\\^IfDisplayFromData2\\|\\^IfEnterKeyPress\\|\\^IfGetCurrentFieldValue\\|\\^IfGetFieldChooseData\\|\\^IfGetFieldChooseDecomp\\|\\^IfGetFieldDecompObject\\|\\^IfGetFieldInternalValue\\|\\^IfGetFieldMessageHandler\\|\\^IfGetFieldObjectsType\\|\\^IfGetFieldPos\\|\\^IfGetFieldResetValue\\|\\^IfGetFieldType\\|\\^IfGetFieldValue\\|\\^IfGetNbFields\\|\\^IfGetPrlgFromTypes\\|\\^IfInitDepth\\|\\^IfKeyCalc\\|\\^IfKeyChoose\\|\\^IfKeyEdit\\|\\^IfKeyInvertCheck\\|\\^IfKeyTypes\\|\\^IfMain\\|\\^IfMain2\\|\\^IfONKeyPress\\|\\^IfPutFieldsOnStack\\|\\^IfReset\\|\\^IfSetAllHelpStrings\\|\\^IfSetAllLabelsMessages\\|"
"\\^FINDELN\\|\\^FLAGACOS2S\\|\\^FLAGASIN2C\\|\\^FLAGASIN2T\\|\\^FLAGATAN2S\\|\\^FLAGAXQ\\|\\^FLAGCHINREM\\|\\^FLAGDERIV\\|\\^FLAGDESOLVE\\|\\^FLAGDIV2\\|\\^FLAGDIV2MOD\\|\\^FLAGDIVPC\\|\\^FLAGEXPAMOD\\|\\^FLAGEXPAND\\|\\^FLAGEXPLN\\|\\^FLAGFACTOR\\|\\^FLAGFACTORMOD\\|\\^FLAGGAUSS\\|\\^FLAGGCD\\|\\^FLAGHALFTAN\\|\\^FLAGHORNER\\|\\^FLAGIBP\\|\\^FLAGIDNTEXEC\\|\\^FLAGILAP\\|\\^FLAGINTVX\\|\\^FLAGJORDAN\\|\\^FLAGLAP\\|\\^FLAGLCM\\|\\^FLAGLDECSOLV\\|\\^FLAGLDSSOLV\\|\\^FLAGLGCD\\|\\^FLAGLIN\\|\\^FLAGLISTEXEC\\|\\^FLAGLNCOLLECT\\|\\^FLAGMATRIXLIMIT\\|\\^FLAGMPOWMOD\\|\\^FLAGNAME\\|\\^FLAGPARTFRAC\\|\\^FLAGPOWMOD\\|\\^FLAGPREVAL\\|\\\\^FLAGPROPFRAC\\|\\^FLAGPTAYL\\|\\^FLAGQXA\\|\\^FLAGRESULTANT\\|\\^FLAGRISCH\\|\\^FLAGSERIES\\|\\^FLAGSEVAL\\|\\^FLAGSIMP2\\|\\^FLAGSINCOS\\|\\^FLAGSUM\\|\\^FLAGSUMVX\\|\\^FLAGSYLVESTER\\|\\^FLAGSYMBEXEC\\|\\^FLAGTAN2SC\\|\\^FLAGTAN2SC2\\|\\^FLAGTCOLLECT\\|\\^FLAGTEXPAND\\|\\^FLAGTLIN\\|\\^FLAGTRIG\\|\\^FLAGTRIGCOS\\|\\^FLAGTRIGSIN\\|\\^FLAGTRIGTAN\\|\\^FLAGTRUNC\\|\\^FLAGTSIMP\\|\\^FLOAT\\?\\|\\^FOURIER\\|\\^FOURIERext\\|\\^FR2ND%\\|\\^FRACPARITY\\|\\^FRND\\|\\^FROMLISText\\|\\^FROOTS\\|\\^FSTR1\\|\\^FSTR10\\|\\^FSTR11\\|\\^FSTR12\\|\\^FSTR13\\|\\^FSTR2\\|\\^FSTR3\\|\\^FSTR4\\|\\^FSTR5\\|\\^FSTR6\\|\\^FSTR7\\|\\^FSTR8\\|\\^FSTR9\\|\\^FTAYL\\|\\^FULLDATA\\|\\^FXNDext\\|\\^FastDiv\\?\\|\\^Filer\\|\\^FindCurVar\\|\\^FontBrowser\\|\\^GAUSS\\|\\^GBASIS\\|\\^GCD1MOD\\|\\^GCDHEUext\\|\\^GCDext\\|\\^GETERABLEMSG\\|\\^GFACTOR\\|\\^GMSOLV\\|\\^GOSPER\\?\\|\\^GREDUCE\\|"
"\\^DUPTYPEZ\\?\\|\\^DeCntMulti\\|\\^DemonicLf\\|\\^DoAlert\\|\\^DoCKeyCancel\\|\\^DoCKeyChAll\\|\\^DoCKeyCheck\\|\\^DoCKeyOK\\|\\^DoCKeyUnChAll\\|\\^DoKeyCancel\\|\\^DoKeyEdit\\|\\^DoKeyOK\\|\\^DoLS\\|\\^DoMKeyOK\\|\\^DoNewMatrixCplx\\|\\^DoNewMatrixReal\\|\\^DoNewMatrixRealOrCplx\\|\\^DoOldMatrixCplx\\|\\^DoOldMatrixReal\\|\\^DupQIsZero\\?\\|\\^DupTypeS\\?\\|\\^DupZIsEven\\?\\|\\^DupZIsNeg\\?\\|\\^DupZIsOne\\?\\|\\^DupZIsTwo\\?\\|\\^E%%>C%%\\|\\^EGCDNEWG\\|\\^EGCDSWAP\\|\\^EGCDext\\|\\^ELMGext\\|\\^EQUALPOS2META\\|\\^EQUALPOSMETA\\|\\^EQUATION\\?\\|\\^EQUIV!\\|\\^EQW3\\|\\^EQW3Code\\|\\^EQW3CursorOff\\|\\^EQW3CursorOn\\|\\^EQW3Edit\\|\\^EQW3GROB\\|\\^EQW3GROBStk\\|\\^EQW3GROBmini\\|\\^EQW3GROBsys\\|\\^EQW3StartEdit\\|\\^EQW3ViewLeft\\|\\^EQW3ViewLeftX\\|\\^EQW3ViewMargin\\|\\^EQW3ViewRight\\|\\^EQW3ViewRightRPL\\|\\^EQW3ViewRightX\\|\\^ERABLEERROR\\|\\^ERR$EVALext\\|\\^EULER\\|\\^EVALUSERFCN\\|\\^EVIDENText\\|\\^EVIDSOLV\\|\\^EXACT\\?\\|\\^EXACTMODE\\|\\^EXACTOFF\\|\\^EXACTON\\|\\^EXLR\\|\\^EXPAMOD\\|\\^EXPANDBOTH\\|\\^EXPANDLN\\|\\^EXPAND\\^\\|\\^EXPEXPA\\|\\^EXPEXPA\\*\\|\\^EXPEXPA\\*1\\|\\^EXPEXPA\\+\\|\\^EXPEXPA-\\|\\^EXPEXPANEG\\|\\^EXPLNext\\|\\^EXPM2EXP\\|\\^ErrBadDim\\|\\^ErrInfRes\\|\\^ErrUndefRes\\|\\^EvalNoCKx\\*\\|\\^EvalNoCKx\\+\\|\\^EvalNoCKx-\\|\\^EvalNoCKx/\\|\\^EvalNoCKxAND\\|\\^EvalNoCKxCHS\\|\\^EvalNoCKxCOMB\\|\\^EvalNoCKxINV\\|\\^EvalNoCKxMOD\\|\\^EvalNoCKxOR\\|\\^EvalNoCKxPERM\\|\\^EvalNoCKxXOR\\|\\^EvalNoCKxXROOT\\|\\^EvalNoCKx\\^\\|\\^FACT1ext\\|\\^FACTOOBJext\\|\\^FACTORACext\\|\\^FACTORS\\|\\^FACTOext\\|\\^FASTREDUCE\\|\\^FCOEF\\|\\^FDEG2ext\\|\\^FEVIDENText\\|\\^FHORNER\\|\\^FILER_MANAGER\\|\\^FILER_MANAGERTYPE\\|"
"\\^CK1Z\\|\\^CK2FPOLY\\|\\^CK2Z\\|\\^CK3Z\\|\\^CKALG\\|\\^CKCARCOMP\\|\\^CKFPOLYext\\|\\^CKINNERCOMP\\|\\^CKINT>0\\|\\^CKLN\\|\\^CKMATRIXELEM\\|\\^CKNUMARRY\\|\\^CKSAMESIZE\\|\\^CKSYMREALCMP\\|\\^CLEANIDLAM\\|\\^CLRCOMPLEX\\|\\^CLREXACT\\|\\^CLRPLUSAT0\\|\\^CMODext\\|\\^CMPLXLN\\|\\^CNORMext\\|\\^COERCE2Z\\|\\^COLC1\\|\\^COLC2\\|\\^COLCext\\|\\^COMPLEX\\?\\|\\^COMPLEXERR\\|\\^COMPLEXMODE\\|\\^COMPLEXOFF\\|\\^COMPLEXON\\|\\^COMPLISText\\|\\^COMPRIMext\\|\\^CONTAINS_LN\\?\\|\\^CONVBACK2INT\\|\\^CONVBACKINT\\|\\^COS2EXPext\\|\\^COS2TAN\\|\\^COS2TAN/2\\|\\^COS2ext\\|\\^COSEXPA\\|\\^COSEXPA\\*\\|\\^COSEXPA\\*1\\|\\^COSEXPA\\+\\|\\^COSEXPA-\\|\\^COSH2EXPext\\|\\^COSTEST\\|\\^CSQFFext\\|\\^CSTFRACTION\\?\\|\\^CURL\\|\\^CXIRext\\|\\^CXRIext\\|\\^CZABS\\|\\^ChangeFocus\\|\\^CheckPNoExt\\|\\^Ck\\&DoMsgBox\\|\\^CombInit\\|\\^CombNext\\|\\^CombProd\\|\\^CombineFac\\|\\^Contains\\?\\|^DEB\\.MATRIX\\|\\^DEB\\.MATRIXTYPE\\|\\^DEG1\\|\\^DEG2ext\\|\\^DEGREext\\|\\^DELTAPSOLVE\\|\\^DENOLCMext\\|\\^DEPTHOBJext\\|\\^DEPTHext\\|\\^DERARG\\|\\^DERIV\\|\\^DERIVIDNT\\|\\^DERIVIDNT1\\|\\^DERIVext\\|\\^DERVX\\|\\^DESOLVE\\|\\^DIMLIMITS\\|\\^DIMRANM\\|\\^DIMS\\|\\^DISPLAYext\\|\\^DISTDIVext\\|\\^DISTRIB\\*\\|\\^DISTRIB/\\|\\^DIV2LISText\\|\\^DIVERGENCE\\|\\^DIVIS\\|\\^DIVISIBLE\\?\\|\\^DIVISext\\|\\^DIVMETAOBJ\\|\\^DIVMOD\\|\\^DIVOBJext\\|\\^DIVPC!\\|\\^DO>STRID\\|\\^DROPZ0\\|\\^DROPZ1\\|\\^DTYPEGAUSSINT\\?\\|\\^DTYPEIRRQ\\?\\|\\^DTYPENDO\\?\\|\\^DTYPFMAT\\?\\|\\^DUPCKLEN{}\\|\\^DUPNULL\\[\\]\\?\\|\\^DUPTYPEGAUSSINT\\?\\|"
"\\^%1TWO\\|\\^%PSI\\|\\^'xPI\\|\\^'xi\\|\\^1\\&meta\\|\\^1-x\\^2/1\\+x\\^2\\|\\^1metainf#\\|\\^1metaundef#\\|\\^2\\*1-cos/sin\\|\\^2\\*sin/1\\+cos\\|\\^2DMATRIX\\?\\|\\^2DROPTRUE\\|\\^2DROPZ0\\|\\^2LAMBIND\\|\\^2POLYNOMIAL\\?\\|\\^2SYMBINCOMP\\|\\^2metainf#\\|\\^2metaundef#\\|\\^2x/1\\+x\\^2\\|\\^3DUP\\|\\^3LAMBIND\\|\\^::POLY\\|\\^>HPOLY\\|\\^>HPOLYN\\|\\^>POLY\\|\\^>POLYTRIM\\|\\^>SIGNE\\|\\^>TPOLY\\|\\^>TPOLYN\\|\\^>VARLIST\\|\\^\\?ext\\|\\^A/B2PQR\\|\\^ABCUV\\|\\^ACOS2ASIN\\|\\^ACOS2LN\\|\\^ACOS2Sext\\|\\^ACOSH2LNext\\|\\^ADDLISText\\|\\^ADDMATOBJext\\|\\^ADDMULTIPL\\|\\^ADDONEVAR\\|\\^ADDTMOD\\|\\^ADDTOREAL\\|\\^ALG48FCTR\\?\\|\\^ALG48MSOLV\\|\\^ALGCASCOMPEVAL\\|\\^ALOG2EXP\\|\\^APPROXCOMPEVAL\\|\\^ARG2\\|\\^ARRAY2MATRIX\\|\\^ARSIZE\\|\\^ASIN2ACOS\\|\\^ASIN2ATAN\\|\\^ASIN2Cext\\|\\^ASIN2LN\\|\\^ASIN2Text\\|\\^ASINH2LNext\\|\\^ATAN2ASIN\\|\\^ATAN2LNext\\|\\^ATAN2Sext\\|\\^ATANH2LNext\\|\\^AXQ\\|\\^AppendList\\|\\^Approx\\|\\^Arbo\\|\\^ArryToList\\|\\^ArryToMatrix\\|\\^BANGARRY\\|\\^BESTDIV2\\|\\^BESTMATRIXTYPE\\|\\^BEZOUTMSOLV\\|\\^BFactor\\|\\^BICARREE\\?\\|\\^BIsPrime\\?\\|\\^BRDispItems\\|\\^BRGetItem\\|\\^BRViewItem\\|\\^BRabin\\|\\^BRdone\\|\\^BRinverse\\|\\^Berlekamp\\|\\^BerlekampP\\|\\^BrentPow\\|\\^BrowseMem\\.1\\|\\^C%%SQRT\\|\\^C%>C%%\\|\\^C2C%%\\|\\^CANTFACTOR\\|\\^CARCOMPext\\|\\^CASCOMPEVAL\\|\\^CASCRUNCH\\|\\^CASFLAGEVAL\\|\\^CASNUMEVAL\\|\\^CDIV2ext\\|\\\\^CFGDISPLAY\\|\\^CGCDext\\|\\^CHECKSING\\|\\^CK%%SQRT\\|\\^CK\\&CONV2INT\\|\\^CK\\&CONVINT\\|\\^CK1Cext\\|\\^CK1TONOext\\|"
"UNTIL\\|UPDIR\\|USER\\$>TAG\\|UStackDepth\\|UnLockAlpha\\|Unbr>U\\|UobROT\\|UserITE\\|UserKeys\\?\\|VARSIZE\\|VERIF_SELECTION\\|VERSTRING\\|VERYSLOW\\|VERYVERYSLOW\\|VLM\\|VSCALE\\|ValidPortTag\\?\\|VerifyTOD\\|ViewEditGrob\\|ViewGrobObject\\|ViewLevel1\\|ViewObject\\|ViewStrObject\\|WHILE\\|WINDOW#\\|WINDOWBOT\\?\\|WINDOWCORNER\\|WINDOWDOWN\\|WINDOWLEFT\\|WINDOWLEFT\\?\\|WINDOWRIGHT\\|WINDOWRIGHT\\?\\|WINDOWTOP\\?\\|WINDOWUP\\|WINDOWXY\\|WIPEOUT\\|WIPESPACE\\|WORDSIZE\\|Wait/GetKey\\|WaitForKey\\|WaitTbz0\\|Warmstart\\|WindowXY\\|WithHidden\\|XEQIOBACKUP\\|XEQORDER\\|XEQPGDIR\\|XEQPURGEPICT\\|XEQRCL\\|XEQSETLIB\\|XEQSHOWLS\\|XEQSTOID\\|XEQStoKey\\|XEQTYPE\\|XHI\\|XHI-1\\|XLINE_SIZE\\?\\|XOR\\|XOR\\$\\|XY>Y\\|XYEX\\|XYGROBDISP\\|XYZ>\\|XYZ>Y\\|XYZ>YXZ\\|XYZ>YZ\\|XYZ>Z\\|XYZ>ZCOLA\\|XYZ>ZTRUE\\|XYZ>ZX\\|XYZ>ZXY\\|XYZ>ZY\\|XYZ>ZYX\\|XYZW>\\|XYZW>W\\|XYZW>WXYZ\\|XYZW>YWZX\\|XYZW>YZWX\\|Y<=X\\|YHI\\|Z<\\|Z<=\\|Z<>\\|Z=\\|Z>\\|Z>=\\|ZERO\\|ZEROFALSE\\|ZEROISTOPSTO\\|ZEROOVER\\|ZEROSWAP\\|ZEROZERO\\|ZEROZEROONE\\|ZEROZEROTWO\\|ZEROZEROZERO\\|ZERO_DO\\|ZoomX\\|ZoomY\\|\\^#3\\+ROLL\\|\\^#>Z\\|\\^#FACT\\|\\^%%PSI\\|"
"TWENTYFIVE\\|TWENTYFOUR\\|TWENTYNINE\\|TWENTYONE\\|TWENTYSEVEN\\|TWENTYSIX\\|TWENTYTHREE\\|TWENTYTWO\\|TWO\\|TWO{}N\\|TYPE\\|TYPEAPLET\\?\\|TYPEARRY\\?\\|TYPEBINT\\?\\|TYPECARRY\\?\\|TYPECHAR\\?\\|TYPECMP\\?\\|TYPECOL\\?\\|TYPECSTR\\?\\|TYPEEXT\\?\\|TYPEFLASHPTR\\?\\|TYPEFONT\\?\\|TYPEGROB\\?\\|TYPEHSTR\\?\\|TYPEIDNT\\|TYPEIDNT\\?\\|TYPELAM\\?\\|TYPELIST\\?\\|TYPELNGCMP\\?\\|TYPELNGREAL\\?\\|TYPERARRY\\?\\|TYPEREAL\\|TYPEREAL\\?\\|TYPEROMP\\?\\|TYPERRP\\?\\|TYPESYMB\\?\\|TYPETAGGED\\?\\|TYPEZINT\\?\\|TakeOver\\|TempConv\\|TestSysFlag\\|TestUserFlag\\|ToGray\\|TogInsertKey\\|TrueFalse\\|TrueTrue\\|TurnOff\\|TurnOffKey\\|U>NCQ\\|U>nbr\\|UART\\?\\|UARTBUFLEN\\|UARTxcp\\|UM#\\?\\|UM%\\|UM%CH\\|UM%T\\|UM\\*\\|UM\\+\\|UM-\\|UM/\\|UM<=\\?\\|UM<\\?\\|UM=\\?\\|UM>=\\?\\|UM>\\?\\|UM>U\\|UMABS\\|UMCEIL\\|UMCHS\\|UMCONV\\|UMCOS\\|UMFLOOR\\|UMFP\\|UMIP\\|UMMAX\\|UMMIN\\|UMRND\\|UMSI\\|UMSIGN\\|UMSIN\\|UMSQ\\|UMSQRT\\|UMTAN\\|UMTRC\\|UMU>\\|UMXROOT\\|UNCOERCE\\|UNCOERCE%%\\|UNCOERCE2\\|UNDO_OFF\\|UNDO_ON\\|UNDO_ON\\?\\|UNIT>\\$\\|UNROLL\\|UNROT\\|UNROT2DROP\\|UNROTDROP\\|UNROTDUP\\|UNROTOVER\\|UNROTSWAP\\|UNROTSWAPDROP\\|"
"SetPrgmEntry\\|SetRebuild\\|SetRightAnn\\|SetServMode\\|SetSomeRow\\|SetSysFlag\\|SetThisRow\\|SetUserFlag\\|SetVStackProtectWord\\|ShowInvRomp\\|Shrink\\$\\|Shrink\\$Any\\|Shrink\\$AnySafe\\|Shrink\\$List\\|Sig\\?ErrJmp\\|SimplifyExpression\\|SolvMenuInit\\|SrvcKbdAB\\|StackFontHeight\\|StackLineHeight\\|StartMenu\\|StartupProc\\|Std/BoxLabel\\|StdIOPAR\\|StdMenuKeyLS\\|StdMenuKeyNS\\|StdPRTPAR\\|StoHiddenVar\\|StoIOPAR\\|StoPRTPAR\\|Str>Menu\\|StrEdit\\|Stretch\\$\\|Stretch\\$Any\\|Sub\\|SubGor\\|SubGxor\\|SubMetaOb\\|SubMetaOb1\\|SubRepl\\|SuspendOK\\?\\|Sys@\\|SysDisplay\\|SysErrorTrap\\|SysErrorTrapAction\\|SysErrorTrapConfirm\\|SysITE\\|SysMenuCheck\\|SysPtr@\\|SysSTO\\|SysTime\\|SystemFlags\\|SystemLevel\\?\\|TAGGED\\|TAGGEDANY\\|TAGOBS\\|TBR\\|TCS\\|TEN\\|THIRTEEN\\|THIRTY\\|THIRTYEIGHT\\|THIRTYFIVE\\|THIRTYFOUR\\|THIRTYNINE\\|THIRTYONE\\|THIRTYSEVEN\\|THIRTYSIX\\|THIRTYTHREE\\|THIRTYTWO\\|THREE\\|THREE{}N\\|TIMEOUT\\?\\|TIMER1\\|TIMER2\\|TIMERCTRL\\.1\\|TIMERCTRL\\.2\\|TIMESTR\\|TOADISP\\|TOD\\|TOD>t\\$\\|TOGDISP\\|TOGGLELINE#3\\|TOGLINE\\|TOGLINE3\\|TOP16\\|TOP8\\|TOPROW\\|TOSRRP\\|TOTEMPOB\\|TOTEMPSWAP\\|TRCXY\\|TRPACKETFAIL\\|TRUE\\|TRUE'\\|TRUEFALSE\\|TST15\\|TURNMENUOFF\\|TURNMENUON\\|TWELVE\\|TWENTY\\|TWENTYEIGHT\\|"
"SWAP2DUP\\|SWAP3PICK\\|SWAP4PICK\\|SWAP4ROLL\\|SWAPCKREF\\|SWAPCOLA\\|SWAPDROP\\|SWAPDROPDUP\\|SWAPDROPSWAP\\|SWAPDROPTRUE\\|SWAPDUP\\|SWAPINCOMP\\|SWAPINDEX@\\|SWAPLOOP\\|SWAPMEM\\|SWAPMEMEQ\\|SWAPMEMEQ_D0D1C\\|SWAPMEM_D0D1C\\|SWAPMEM_D0D1C_nofree\\|SWAPMEM_D0D1D\\|SWAPMEM_D0D1D_nofree\\|SWAPMEM_nofree\\|SWAPONE\\|SWAPOVER\\|SWAPOVER#-\\|SWAPROT\\|SWAPTRUE\\|SWAPUnDROP\\|SWAPUnNDROP\\|SWAPcompSWAP\\|SWP1\\+\\|SYMBN\\|SYMBNUMSOLVE\\|SYMBREAL\\|SYMBUNIT\\|SYMEXT\\|SYMID\\|SYMLAM\\|SYMOB\\|SYMREAL\\|SYMSHOW\\|SYMSYM\\|SYNTAXERR\\|SYSCONTEXT\\|SYSRRP\\?\\|SavPtrTime\\*\\|SaveLastEdit\\|SaveLastMenu\\|SaveSysFlags\\|SaveVarRes\\|ScanEveryObjects\\|ScrollVGrob\\|Seco>Menu\\|SendSetup\\|SetAlgEntry\\|SetAlphaAnn\\|SetAppMode\\|SetAppSuspOK\\|SetBadPOLUI\\|SetCursor\\|SetDA123NoCh\\|SetDA12NoCh\\|SetDA12Temp\\|SetDA12a3NCh\\|SetDA13NoCh\\|SetDA1Bad\\|SetDA1IsStat\\|SetDA1NoCh\\|SetDA1Temp\\|SetDA1Valid\\|SetDA23NoCh\\|SetDA2NoCh\\|SetDA2OKTemp\\|SetDA2Valid\\|SetDA2aBad\\|SetDA2aEcho\\|SetDA2aNoCh\\|SetDA2aTemp\\|SetDA2aValid\\|SetDA2bBad\\|SetDA2bIsEdL\\|SetDA2bNoCh\\|SetDA2bTemp\\|SetDA2bTempF\\|SetDA2bValid\\|SetDA3Bad\\|SetDA3NoCh\\|SetDA3Temp\\|SetDA3Valid\\|SetDA3ValidF\\|SetDAsNoCh\\|SetDAsTemp\\|SetDoStdKeys\\|SetEcma94\\|SetHeader\\|SetHiddenRes\\|SetIOPARErr\\|SetISysFlag\\|SetKeysNS\\|SetLeftAnn\\|SetNAppKeyOK\\|SetNoRollDA2\\|"
"SENDACK\\|SENDEOT\\|SENDERROR\\|SENDLIST\\|SENDNAK\\|SENDNULLACK\\|SENDPKT\\|SEP\\$NL\\|SET\\|SETCIRCERR\\|SETCURSOR\\|SETDEG\\|SETFIRSTC_0\\|SETGRAD\\|SETHASH\\|SETIVLERR\\|SETLOOPENV\\|SETMEMERR\\|SETMESG\\|SETNONEXTERR\\|SETPORTNOTAV\\|SETRAD\\|SETROMPART\\|SETROMPERR\\|SETSIZEERR\\|SETSTACKERR\\|SETTYPEERR\\|SET_HEADER\\|SEVEN\\|SEVENROLL\\|SEVENTEEN\\|SEVENTY\\|SEVENTYFOUR\\|SEVENTYNINE\\|SIX\\|SIXROLL\\|SIXTEEN\\|SIXTY\\|SIXTYEIGHT\\|SIXTYFOUR\\|SIXTYONE\\|SIXTYTHREE\\|SIXTYTWO\\|SIXUNROLL\\|SIZEPLUS\\|SKIP\\|SKIPOB\\|SLEEPxcp\\|SLOW\\|SORTASLOW\\|SPACE$\\|SPLITA\\|SPLITWHERE\\|SPLTAC\\|SQRF\\|STAB0\\|STAB2\\|STATCLST\\|STATMEAN\\|STATN\\|STATSADD%\\|STATSMAX\\|STATSMIN\\|STATSTDEV\\|STATTOT\\|STATVAR\\|STCD0\\|STCD2\\|STO\\|STO'\\|STOALM\\|STOAPPLDATA\\|STOFONT\\|STOLAM\\|STOMINIFONT\\|STO_CMD_MODE\\|STO_CURS_POS\\|STO_CURS_POS2\\|STO_CURS_POS3\\|STO_CURS_POS4\\|STO_CURS_POS_VIS\\|STO_ML_DISP_SIZE\\|STRIPTAGS\\|STRIPTAGSl2\\|STRLIST\\|STYLE.MINIFONT\\|SUB$\\|SUB\\$1#\\|SUB\\$SWAP\\|SUBCOMP\\|SUBGROB\\|SUBHXS\\|SWAP\\|SWAP#-\\|SWAP#1\\+\\|SWAP#1\\+SWAP\\|SWAP#1-\\|SWAP#1-SWAP\\|SWAP%%/\\|SWAP%>C%\\|SWAP\\&$\\|SWAP'\\|"
"RDROP\\|RDROPCOLA\\|RDROPFALSE\\|RDUP\\|REALEXT\\|REALOB\\|REALOBOB\\|REALREAL\\|REALSYM\\|REALcase\\|RECLAIMDISP\\|RECORDX\\&YC%\\|REMAP\\|REPEAT\\|REPEATER\\|REPEATERCH\\|REPKEY\\?\\|REPLACE\\|REPLACEALL\\|REPLACEALLNOSCREEN\\|REPLACE_MODE\\|REQcase\\|REQcasedrop\\|RESETDEPTH\\|RESOROMP\\|RIGHT\\$3x6\\|RIGHTCOL\\|RNDC\\[B\\]\\|RNDXY\\|ROLL\\|ROLLDROP\\|ROLLSWAP\\|ROM-WORD\\?\\|ROMPANY\\|ROMPTR>#\\|ROMPTR@\\|ROOM\\|ROT\\|ROT#\\+\\|ROT#\\+SWAP\\|ROT#-\\|ROT#1\\+\\|ROT#1\\+UNROT\\|ROT\\+SWAP\\|ROT2DROP\\|ROT2DUP\\|ROTAND\\|ROTDROP\\|ROTDROPSWAP\\|ROTDUP\\|ROTOVER\\|ROTROT2DROP\\|ROTSWAP\\|ROTUntop\\&\\|RPIT\\|RPITE\\|RPNDecomp#Disp\\|RPNDecomp#Line\\|RPNDecomp1Line\\|RPNDecompEcho\\|RPNDecompEdit\\|RPNDecompStd1Line\\|RPNDecompStd1Line32\\|RSKIP\\|RSUB1\\|RSWAP\\|Rcl\\&Do:\\|RclAssembly\\|RclCompareNames\\|RclHiddenVar\\|Re>C%\\|Repl\\|RestVarRes\\|RestoreSysFlags\\|ReviewKey!\\|Roll\\&Do:\\|Rom-Word\\?\\|Rows8-15\\|RunInApprox\\|RunRPN:\\|RunSafeFlags\\|RunSafeFlagsNoError\\|SAFE@\\|SAFE@_HERE\\|SAFESKIPOB\\|SAFESTO\\|SAVELAM\\|SAVESTACK\\|SAVPTR\\|SCAN\\.FONTE\\|SCANFONT\\|SCREEN\\.MARGIN\\|SCREEN\\.MARGIN2\\|SCROLLDOWN\\|SCROLLLEFT\\|SCROLLRIGHT\\|SCROLLUP\\|SELECT\\.FONT\\|SELECT\\.LINE\\|SELECT\\.LINEEND\\|SEMI\\|SEMILOOP\\|"
"PRLG\\|PTYPE>PINFO\\|PULLCMPEL\\|PULLREALEL\\|PURGALARM%\\|PURGE\\|PUSH#\\|PUSH#ALOOP\\|PUSH#LOOP\\|PUSH%\\|PUSH%LOOP\\|PUSH2#\\|PUSHA\\|PUSHC%\\|PUSHC%%\\|PUSHhxs\\|PUSHhxsLoop\\|PUSHzint\\|PUSHzintLoop\\|PUTAB0\\|PUTCMPEL\\|PUTEL\\|PUTINDEP\\|PUTINDEPLIST\\|PUTLAM\\|PUTLIST\\|PUTPTYPE\\|PUTREALEL\\|PUTRES\\|PUTSCALE\\|PUTSERIAL\\|PUTXMAX\\|PUTXMIN\\|PUTYMAX\\|PUTYMIN\\|PUT_FONTE\\|PUT_STYLE\\|ParOuterLoop\\|Parse\\.1\\|Parse\\.2\\|ParseFail\\|ParseFail2\\|PixonB\\|PixonG1\\|PixonG2\\|PixonW\\|PixonXor\\|PlotOneMore\\?\\|PopASavptr\\|PopMetaVStack\\|PopMetaVStackDROP\\|PopSavptr\\|PopVStack\\|PopVStackAbove\\|PrevNonNull\\|PrgmEntry\\?\\|PrintGrob\\|PromptIdUtil\\|PtoR\\|PuHiddenVar\\|Push#FLoop\\|Push#TLoop\\|Push2#Loop\\|Push2#aLoop\\|PushF/TLoop\\|PushFLoop\\|PushMetaVStack\\|PushMetaVStack&Drop\\|PushT/F\\|PushT/FLoop\\|PushTLoop\\|PushVStack\\|PushVStack\\&Clear\\|PushVStack\\&Keep\\|PushVStack&KeepDROP\\|PutElemBotVStack\\|PutElemTopVStack\\|P{}N\\|R>\\|R@\\|RAD\\?\\|RADD1\\|RADDF\\|RAM-WORDNAME\\|RBR\\|RCAB0\\|RCAB2\\|RCCD0\\|RCCD2\\|RCKBp\\|RCLALARM%\\|RCLSYSF\\|RCLUSERF\\|RCL_CMD\\|RCL_CMD2\\|RCL_CMD_DEB\\|RCL_CMD_FIN\\|RCL_CMD_MODE\\|RCL_CMD_POS\\|RCL_NB_AFF_LGN\\|RCL_NB_AFF_LGNSTK\\|RCS\\|"
"NUMSOLVE\\|NcaseSIZEERR\\|NcaseTYPEERR\\|NoAttn\\?Semi\\|NoEdit\\?case\\|NoEditLine\\?\\|NoExitAction\\|NoIgnoreAlm\\|NullMenuKey\\|OB>BAKcode\\|OCRC\\|OCRC%\\|OFFSRRP\\|ONE\\|ONE#>\\|ONECOLA\\|ONEDUP\\|ONEFALSE\\|ONEFALSE'\\|ONEHUNDRED\\|ONEONE\\|ONESWAP\\|ONE_DO\\|ONE_EQ\\|ONE{}N\\|OR\\|OR\\$\\|ORDERXY#\\|ORDERXY%\\|ORNOT\\|ORcase\\|OSIZE\\|OUTCINRTN\\|OVER\\|OVER#\\+\\|OVER#-\\|OVER#0=\\|OVER#2\\+UNROL\\|OVER#<\\|OVER#=\\|OVER#=case\\|OVER#>\\|OVER'\\|OVER5PICK\\|OVERARSIZE\\|OVERDUP\\|OVERINDEX@\\|OVERLEN\\$\\|OVERSWAP\\|OVERUNROT\\|Ob>Seco\\|ObEdit\\|OnKeyDown\\?\\|OnKeyStable\\?\\|OngoingText\\?\\|OpenIO\\|OpenIOPrt\\|OpenUart\\?Clr\\|OpenUartClr\\|OverWrF/TLp\\|OverWrFLoop\\|OverWrT/FLp\\|OverWrTLoop\\|PACK\\|PACKSB\\|PALPTRDCMP\\|PASTE\\.EXT\\|PATHDIR\\|PI/180\\|PICK\\|PICTRCL\\|PIXOFF\\|PIXOFF3\\|PIXON\\|PIXON3\\|PIXON\\?\\|PIXON\\?3\\|PLOTERR\\|PLOTPREP\\|POLErrorTrap\\|POLKeyUI\\|POLResUI\\&Err\\|POLRestoreUI\\|POLSaveUI\\|POLSetUI\\|POP#\\|POP1%\\|POP1%SPLITA\\|POP2#\\|POP2%\\|POPC%\\|POPC%%\\|POPKEY\\|POS\\$\\|POS\\$REV\\|POSCHR\\|POSCHRREV\\|POSCOMP\\|PREMARKON\\|PREVRAM-WORD\\|PRINT\\|PRINTxNLF\\|"
"MENP\\&FixDA12\\|MENUOFF\\|MENUOFF\\?\\|MENoP\\&FixDA1\\|MEQ1stcase\\|MEQopscase\\|MINIFONT>\\|MINI_DISP\\|MINI_DISP_AWP\\|MINI_DISP_PARAM\\|MINI_DISP_VAL\\|MINUSONE\\|MOVEDOWN\\|MOVEDSD\\|MOVEDSU\\|MOVERSD\\|MOVERSU\\|MOVEUP\\|MOVEVAR\\|MPY\\|MUL#\\|MULTB\\+A*C\\|MULTBAC\\|MULTF\\|MYRAMROMPAIR\\|MakeBoxLabel\\|MakeDirLabel\\|MakeInvLabel\\|MakeLabel\\|MakeStdLabel\\|MenuDef@\\|MenuKey\\|MenuKeyLS!\\|MenuKeyNS!\\|MenuKeyNS@\\|MenuKeyRS!\\|MenuMaker\\|MenuRow!\\|MenuRow@\\|MenuRowAct!\\|Mid1stcase\\|MiniFontCmd\\?\\|MiniFontStk\\?\\|Modifier\\|ModifierKey\\?\\|N\\+1DROP\\|NDROP\\|NDROPFALSE\\|NDUP\\|NDUPN\\|NEWACCESSRAM\\|NEWADR\\|NEWINDEP\\|NEWLINE\\$\\|NEWLINE\\$\\&\\$\\|NEWLINE\\&\\$\\|NEWMARK\\|NEXTCOMPOB\\|NEXTIRQ\\|NEXTLIBBAK\\|NEXTRRPOB\\|NEXTSTEP\\|NINE\\|NINETEEN\\|NOBLINK\\|NOHALTERR\\|NOP\\|NOT\\|NOT\\?DROP\\|NOT\\?GOTO\\|NOT\\?SEMI\\|NOT\\?SWAPDROP\\|NOTAND\\|NOTLISTcase\\|NOTROMPcase\\|NOTSECOcase\\|NOT_IT\\|NOT_UNTIL\\|NOT_WHILE\\|NOTcase\\|NOTcase2DROP\\|NOTcase2drop\\|NOTcaseDROP\\|NOTcaseFALSE\\|NOTcaseTRUE\\|NOTcasedrop\\|NOTcsdrpfls\\|NO_AFFCMD\\|NTHCOMDDUP\\|NTHCOMPDROP\\|NTHELCOMP\\|NTHOF\\|NULL$\\|NULL\\$\\?\\|NULL\\$SWAP\\|NULL\\$TEMP\\|NULL::\\|NULLCOMP\\?\\|NULLHXS\\|NULLID\\|NULLLAM\\|NULL{}\\|"
"InitPOLVars\\|InitSysUI\\|InitTrack:\\|InitVirtualStack\\|Init_MetaKernelFont\\|InputLAttn\\|InputLEnter\\|InputLine\\|InsertEcho\\|IntDiv\\|InverseParcelle\\|JINDEX@\\|JINDEXSTO\\|JSTOP@\\|JSTOPSTO\\|JUMPBOT\\|JUMPLEFT\\|JUMPRIGHT\\|JUMPTOP\\|JstGETTHEMSG\\|KDispRow2\\|KDispStatus2\\|KERMOPEN\\|KEYINBUFFER\\?\\|KILLGDISP\\|KINVISLF\\|KVIS\\|KVISLF\\|KeepUnit\\|Key>StdKeyOb\\|Key>U/SKeyOb\\|KeyInBuff\\?\\|KeyOb!\\|KeyOb0\\|KeyOb@\\|Keyword\\?\\|LAMLNAME\\|LANGUAGE>\\|LAST\\$\\|LASTARGCOUNT\\|LASTPT\\?\\|LASTRAM-WORD\\|LBoxB\\|LBoxG1\\|LBoxG2\\|LBoxW\\|LBoxXor\\|LEFT\\$3x5\\|LEFT\\$3x5Arrow\\|LEFT\\$3x5CR\\|LEFT\\$3x5CRArrow\\|LEFT\\$5x7\\|LEFT\\$5x7Arrow\\|LEFT\\$5x7CR\\|LEFT\\$5x7CRArrow\\|LEFTCOL\\|LEN\\$\\|LENCOMP\\|LENHXS\\|LINECHANGE\\|LINEOFF\\|LINEOFF3\\|LINEON\\|LINEON3\\|LISTCMP\\|LISTLAM\\|LISTRCL\\|LISTREAL\\|LOOP\\|LabelDef!\\|LastMenuDef!\\|LastMenuDef@\\|LastMenuRow!\\|LastMenuRow@\\|LastNonNull\\|Lift\\|LineB\\|LineG1\\|LineG2\\|LineW\\|LineXor\\|List\\|LoadTouchTbl\\|LockAlpha\\|Lookup\\|Lookup\\.1\\|Loop\\|LowBat\\?\\|M-1stcasechs\\|MACRODCMP\\|MAKE\\$\\|MAKE\\$N\\|MAKEBOT\\$N\\|MAKEGROB\\|MAKEPICT#\\|MAKEPVARS\\|MAKERAM\\$\\|MARKGROB\\|MATATLOOP\\|MDIMSDROP\\|MEM\\|MEMERR\\|"
"GROB>GDISP\\|GROBDIM\\|GROBDIMw\\|GetBankAccess\\|GetChkPRTPAR\\|GetElemBotVStack\\|GetElemTopVStack\\|GetEqN\\|GetFontCmdHeight\\|GetFontHeight\\|GetFontStkHeight\\|GetHeader\\|GetIOPAR\\|GetKermPkt#\\|GetKeyOb\\|GetLastEdit\\|GetMenu%\\|GetMetaVStack\\|GetMetaVStackDROP\\|GetNextToken\\|GetRes\\|GetStrLen\\|GetStrLenC\\|GetStrLenL\\|GetStrLenStk\\|GetTimChk\\|GetTime\\+\\+\\|GetUserKeys\\|GetVStack\\|GetVStackProtectWord\\|Gor\\|GraphicExit\\|Grey\\?\\|Grob>Menu\\|GsstFIN\\|Gxor\\|H/W>KeyCode\\|H/WKey>KeyOb\\|HARDBUFF\\|HARDBUFF2\\|HARDHEIGHT\\|HBUFF_X_Y\\|HEIGHTENGROB\\|HEXTODEC\\|HISTON\\?\\|HOMEDIR\\|HSCALE\\|HXDCW\\|HXS#HXS\\|HXS<=HXS\\|HXS<HXS\\|HXS==HXS\\|HXS>#\\|HXS>\\$\\|HXS>%\\|HXS>=HXS\\|HXS>HXS\\|ICMPDRPRTDRP\\|ID>\\$\\|ID>TAG\\|IDREAL\\|IDUP\\|INCOMPDROP\\|INDEPVAR\\|INDEX@\\|INDEX@#-\\|INDEXSTO\\|INHARDROM\\?\\|INITMKFONT\\|INIT_AFFICHELIGNE\\|INIT_AFFICHELIGNENORM\\|INNER#1=\\|INNERCOMP\\|INNERDUP\\|INSERT\\?\\|INSERT_MODE\\|INTEGER337\\|INTEMNOTREF\\?\\|INV\\.ZONE\\|INVGROB\\|IOC\\|IOCheckReal\\|IOCsave\\|IRAM@\\|IRAMBUFF\\|IRC\\|ISTOP-INDEX\\|ISTOP@\\|ISTOPSTO\\|IT\\|ITE\\|ITE_DROP\\|Id>Menu\\|ImmedEntry\\?\\|IncrLAMPKNO\\|InitEd\\&Modes\\|InitEdLine\\|InitEdModes\\|InitEnab\\|InitIOEnv\\|InitMenu\\|InitMenu%\\|"
"FORTYTWO\\|FOUR\\|FOURFIVE\\|FOURROLL\\|FOURROLLROT\\|FOURTEEN\\|FOURTHREE\\|FOURTWO\\|FOURTY\\|FOURUNROLL\\|FSCANFONT\\|FalseFalse\\|FalseTrue\\|FcnUtilEnd\\|Find1stT\\.1\\|Find1stTrue\\|FindInDir\\|FindNext\\|FindStrInCmd\\|FixRRP\\|FlashMsg\\|FlashROMTAB2\\|FlashWarning\\|Flush\\|FlushAttn\\|GARBAGE\\|GARBAGECOL\\|GBUFF\\|GBUFFGROBDIM\\|GDISPCENTER\\|GET\\.FONT\\|GET\\.W->\\|GET\\.W<-\\|GETAB0\\|GETAB1\\|GETATELN\\|GETBOTTEMP\\|GETCD0\\|GETDF\\|GETEXITMSG\\|GETINDEP\\|GETKEY\\|GETKEY\\*\\|GETKP\\|GETLAM\\|GETLAMPAIR\\|GETNAME\\|GETPARAM\\|GETPMIN\\&MAX\\|GETPROC\\|GETPTR\\|GETPTRFALSE\\|GETPTRLOOP\\|GETPTRTRUE\\|GETPTYPE\\|GETRES\\|GETRHS\\|GETRRP\\|GETSCALE\\|GETSERIAL\\|GETTEMP\\|GETTHEMESG\\|GETTOUCH\\|GETX\\.VISIBLE\\|GETX\\.VISIBLE\\.STR\\|GETXMAX\\|GETXMIN\\|GETXPOS\\|GETYMAX\\|GETYMIN\\|GETYPOS\\|GET_@FONTE\\|GET_@TAB\\|GET_ATTRIBN\\.REAL\\|GET_CUR_FONT\\.EXT\\|GET_HEADER\\|GET_HEADERTYPE\\|GET_HFONTE\\|GET_HFONTECMD\\|GET_HFONTESTK\\|GET_HFONTESTKD1C\\|GET_NBLIGNE\\|GET_NBLIGNESTK\\|GOTO\\|GOTOLABEL\\|GPErrjmpC\\|GPMEMERR\\|GPOverWrALp\\|GPOverWrFLp\\|GPOverWrR0Lp\\|GPOverWrT/FL\\|GPOverWrTLp\\|GPPushA\\|GPPushALp\\|GPPushFLoop\\|GPPushR0Lp\\|GPPushT/FLp\\|GPPushTLoop\\|GROB!\\|GROB!ZERO\\|GROB!ZERODRP\\|GROB\\+#\\|"
"EQOR\\|EQOVER\\|EQUAL\\|EQUALNOT\\|EQUALNOTcase\\|EQUALOR\\|EQUALPOSCOMP\\|EQUALcase\\|EQUALcasedrop\\|EQUALcasedrp\\|EQUATION\\|EQcase\\|EQcasedrop\\|ERASE&LEFT\\$3x5\\|ERASE\\&LEFT\\$5x7\\|ERRBEEP\\|ERRJMP\\|ERROR@\\|ERRORCLR\\|ERROROUT\\|ERRORSTO\\|ERRSET\\|ERRTRAP\\|EVAL\\|EVAL\\.LINE\\|EVAL\\.SELECTION\\|EVALCRUNCH\\|EXAB0\\|EXAB2\\|EXCHINITPK\\|EXEC_CMD\\|EXITMSGSTO\\|EXPAND\\|EXT\\|EXTN\\|EXTOBOB\\|EXTREAL\\|EXTSYM\\|Echo\\$Key\\|Echo\\$NoChr00\\|Echo2Macros\\|EchoChrKey\\|EditExstCase\\|EditFont\\|EditLExists\\?\\|EditLevel1\\|EditMenu\\|EditSelect\\|EditString\\|Embedded\\?\\|EndTempOb\\|EqList\\?\\|Errjmp\\|ErrjmpC\\|ErrorHandled\\?\\|EvalNoCK\\|EvalParsed\\|ExitAction!\\|ExitAtLOOP\\|ExitFcn\\|Extobcode\\|FALSE\\|FALSE'\\|FALSETRUE\\|FBoxB\\|FBoxG1\\|FBoxG2\\|FBoxXor\\|FIFTEEN\\|FIFTY\\|FIFTYEIGHT\\|FIFTYFIVE\\|FIFTYFOUR\\|FIFTYNINE\\|FIFTYONE\\|FIFTYSEVEN\\|FIFTYSIX\\|FIFTYTHREE\\|FIFTYTWO\\|FIRSTC\\+\\|FIRSTC@\\|FIVE\\|FIVEFOUR\\|FIVEROLL\\|FIVESIX\\|FIVETHREE\\|FIVEUNROLL\\|FLOAT\\|FLUSH\\|FLUSHKEYS\\|FLUSHRSBUF\\|FNDALARM{}\\|FONT>\\|FORTY\\|FORTYEIGHT\\|FORTYFIVE\\|FORTYFOUR\\|FORTYNINE\\|FORTYONE\\|FORTYSEVEN\\|FORTYSIX\\|FORTYTHREE\\|"
"DUPTYPEIDNT\\?\\|DUPTYPELAM\\?\\|DUPTYPELIST\\?\\|DUPTYPELNGCMP\\?\\|DUPTYPELNGREAL\\?\\|DUPTYPEREAL\\?\\|DUPTYPEROMP\\?\\|DUPTYPERRP\\?\\|DUPTYPESYMB\\?\\|DUPTYPETAG\\?\\|DUPTYPEZINT\\?\\|DUPUNROT\\|DUPZERO\\|DZP\\|DaDGNTc\\|Date>d\\$\\|Date>hxs13\\|Day>Date\\|DcompWidth@\\|Debounce\\|Decomp#Disp\\|Decomp#Line\\|Decomp%Short\\|Decomp1Line\\|DecompEcho\\|DecompEdit\\|DecompStd1Line\\|DecompStd1Line32\\|DeepSleep\\|DisableIntr\\|Disp5x7\\|DispBadToken\\|DispBadToken2\\|DispCommandLine\\|DispCoord1\\|DispEditLine\\|DispILPrompt\\|DispMenu\\|DispMenu\\.1\\|DispOff\\|DispOn\\|DispStatus\\|DispStsBound\\|DispTime\\?\\|DispTimeReq\\?\\|DispVarsUtil\\|Distance\\|Dither\\|Do1st/2nd\\+:\\|DoBadKey\\|DoCAlarmKey\\|DoCRC\\|DoCRCc\\|DoDelim\\|DoDelims\\|DoFarBS\\|DoFarDel\\|DoFirstRow\\|DoHere:\\|DoInputForm\\|DoKeyOb\\|DoLabel\\|DoMenuKey\\|DoMenuKeyNS\\|DoNameKeyLRS\\|DoNameKeyRS\\|DoNewEqw\\|DoNewMatrix\\|DoNextRow\\|DoOldMatrix\\|DoPlotMenu\\|DoPrevRow\\|DoRunSafe\\|DoSolvrMenu\\|DoStdKeys\\?\\|DoWarning\\|DropBadKey\\|DropLoop\\|DropSysErr\\$\\|DropSysObs\\|DropVStack\\|DupAndThen\\|ECUSER\\|EDITDECOMP\\$\\|EDITF\\|EDITLINE\\|EDITLINE\\$\\|EDITPARTS\\|EIGHT\\|EIGHTEEN\\|EIGHTROLL\\|EIGHTY\\|EIGHTYONE\\|ELEVEN\\|ENCODE\\|ENCODE1PKT\\|EQ\\|EQ:\\|EQCURSOR\\?\\|EQIT\\|EQITE\\|EQLookup\\|"
"DOREPLACE/NEXT\\|DOROMP\\|DORRP\\|DOSBRK\\|DOSCI\\|DOSIZEERR\\|DOSRECV\\|DOSTD\\|DOSTOALLF\\|DOSTOE\\|DOSTOSYSF\\|DOSTR>\\|DOSYMB\\|DOTAG\\|DOTEXTINFO\\|DOTRANSIO\\|DOTRUE\\|DOTVARS%\\|DOVARS\\|DPRADIX\\?\\|DRAWBOX#\\|DRAWLINE#3\\|DROP\\|DROP#1-\\|DROP'\\|DROP3PICK\\|DROPDEADTRUE\\|DROPDUP\\|DROPFALSE\\|DROPLOOP\\|DROPNDROP\\|DROPNULL\\$\\|DROPONE\\|DROPOVER\\|DROPRDROP\\|DROPROT\\|DROPSWAP\\|DROPSWAPDROP\\|DROPTRUE\\|DROPZERO\\|DTYPEARRY\\?\\|DTYPECOL\\?\\|DTYPECSTR\\?\\|DTYPELIST\\?\\|DTYPEREAL\\?\\|DUMP\\|DUP\\|DUP#0<>\\|DUP#0<>WHILE\\|DUP#0=\\|DUP#0=IT\\|DUP#0=ITE\\|DUP#0=case\\|DUP#0=csDROP\\|DUP#0=csedrp\\|DUP#0_DO\\|DUP#1\\+\\|DUP#1\\+PICK\\|DUP#1-\\|DUP#1=\\|DUP#2\\+\\|DUP#<7\\|DUP$>ID\\|DUP%0=\\|DUP'\\|DUP1LAMBIND\\|DUP3PICK\\|DUP3PICK#\\+\\|DUP4PUTLAM\\|DUP4UNROLL\\|DUP@\\|DUPDUP\\|DUPEQ:\\|DUPGROBDIM\\|DUPINCOMP\\|DUPINDEX@\\|DUPLEN\\$\\|DUPLENCOMP\\|DUPNULL\\$\\?\\|DUPNULLCOMP\\?\\|DUPNULL{}\\?\\|DUPONE\\|DUPPICK\\|DUPROLL\\|DUPROM-WORD\\?\\|DUPROMPTR@\\|DUPROT\\|DUPSAFE@\\|DUPTEMPENV\\|DUPTWO\\|DUPTYPEAPLET\\?\\|DUPTYPEARRY\\?\\|DUPTYPEBINT\\?\\|DUPTYPECHAR\\?\\|DUPTYPECMP\\?\\|DUPTYPECOL\\?\\|DUPTYPECSTR\\?\\|DUPTYPEEXT\\?\\|DUPTYPEFLASHPTR\\?\\|DUPTYPEFONT\\?\\|DUPTYPEGROB\\?\\|DUPTYPEHSTR\\?\\|"

;"DISPLASTROW\\|DISPLASTROWBUT1\\|DISPN\\|DISPROW1\\|DISPROW1\\*\\|DISPROW10\\|DISPROW2\\|DISPROW2\\*\\|DISPROW3\\|DISPROW4\\|DISPROW5\\|DISPROW6\\|DISPROW7\\|DISPROW8\\|DISPROW9\\|DISPSTATUS2\\|DISP_DEC\\|DISP_LINE\\|DIV2\\|DIV5\\|DIVF\\|DO\\|DO#EXIT\\|DO\\$EXIT\\|DO%EXIT\\|DO<Del\\|DO<Skip\\|DO>BEG\\|DO>Del\\|DO>END\\|DO>LCD\\|DO>STR\\|DO>Skip\\|DOACPTR\\|DOAPLET\\|DOARRY\\|DOBAK\\|DOBAUD\\|DOBEEP\\|DOBIN\\|DOBIND\\|DOBINT\\|DOBUFLEN\\|DOC>PX\\|DOCHAR\\|DOCHR\\|DOCLLCD\\|DOCMP\\|DOCODE\\|DOCOL\\|DOCR\\|DOCSTR\\|DODEC\\|DODEL\\.L\\|DODELAY\\|DODISP\\|DOECMP\\|DOENG\\|DOERASE\\|DOEREL\\|DOEXT\\|DOEXT0\\|DOEXT1\\|DOEXT2\\|DOEXT3\\|DOEXT4\\|DOFALSE\\|DOFIND\\|DOFINISH\\|DOFIX\\|DOFLASHP\\|DOGARBAGE\\|DOGRAPHIC\\|DOGROB\\|DOHEX\\|DOHSTR\\|DOHXS\\|DOIDNT\\|DOINT\\|DOKERRM\\|DOLAM\\|DOLCD>\\|DOLIB\\|DOLIST\\|DOLNGCMP\\|DOLNGREAL\\|DOLNKARRY\\|DOMATRIX\\|DOMEMERR\\|DOMINIFONT\\|DONEXT\\|DOOCT\\|DOOPENIO\\|DOPARITY\\|DOPKT\\|DOPRLCD\\|DOPX>C\\|DORANDOMIZE\\|DORCLE\\|DOREAL\\|DOREPL\\|DOREPLACE\\|"

;"ClrDA2bIsEdL\\|ClrDA2bNoCh\\|ClrDA2bOK\\|ClrDA2bTemp\\|ClrDA3Bad\\|ClrDA3OK\\|ClrDAsOK\\|ClrDouseAlm\\|ClrLeftAnn\\|ClrNewEditL\\|ClrNoRollDA2\\|ClrRightAnn\\|ClrServMode\\|ClrSysFlag\\|ClrUserFlag\\|CodePl>%rc\\.p\\|Coldstart\\|CommandLineHeight\\|CompareACbBytes\\|ComputePixel\\|Connecting\\|CtlAlarm!\\|CtlAlarm@\\|CurROMBank2\\|D/D\\*\\|D/D\\+\\|D/D-\\|D/D/\\|D/D=\\|D/DABS\\|D/DACOS\\|D/DACOSH\\|D/DALOG\\|D/DAPPLY\\|D/DARG\\|D/DASIN\\|D/DASINH\\|D/DATAN\\|D/DATANH\\|D/DCHS\\|D/DCONJ\\|D/DCOS\\|D/DCOSH\\|D/DDER\\|D/DEXP\\|D/DEXPM1\\|D/DIFTE\\|D/DINTEGRAL\\|D/DINV\\|D/DLN\\|D/DLNP1\\|D/DLOG\\|D/DSIN\\|D/DSINH\\|D/DSQ\\|D/DSQRT\\|D/DSUM\\|D/DTAN\\|D/DTANH\\|D/DWHERE\\|D/D\\^\\|D/D\\^X\\|D/D\\^Y\\|D/Dalg=\\|D0->Row1\\|D0->Sft1\\|D0=ALoop\\|D0=DSKTOP\\|D1=DSKTOP\\|DA1Bad\\?\\|DA1IsStatus\\?\\|DA1OK\\?\\|DA1OK\\?NOTIT\\|DA2aBad\\?\\|DA2aLess1OK\\?\\|DA2aOK\\?NOTIT\\|DA2bBad\\?\\|DA2bIsEdL\\?\\|DA2bNoCh\\?\\|DA2bOK\\?NOTIT\\|DA2bTemp\\?\\|DA3Bad\\?\\|DA3OK\\?\\|DA3OK\\?NOTIT\\|DATE\\|DATE\\+DAYS\\|DAY#\\|DBUG\\|DBUG\\.TOUCHE\\|DCHXW\\|DDAYS\\|DECODE\\|DECOMP\\$\\|DEEPSLEEP\\|DEL_CMD\\|DEPTH\\|DEPTHSAVE\\|DISP@01\\|DISP@09\\|DISP@17\\|DISP@25\\|DISPCOORD2\\|"
;"CLEARVDISP\\|CLKADJ\\*\\|CLKTICKS\\|CLOSEUART\\|CLRFRC\\|CMDSIZE\\|CMDSTO\\|CMD_BAK\\|CMD_COPY\\|CMD_COPY\\.SBR\\|CMD_CUT\\|CMD_DEB_LINE\\|CMD_DEL\\|CMD_DOWN\\|CMD_DROP\\|CMD_END_LINE\\|CMD_NXT\\|CMD_PAGED\\|CMD_PAGEL\\|CMD_PAGER\\|CMD_PAGEU\\|CMD_PLUS\\|CMD_PLUS2\\|CMD_PLUS3\\|CMD_STO_DEBUT\\|CMD_STO_FIN\\|CMD_UP\\|CMULT34\\|COERCE\\|COERCE\\$22\\|COERCE2\\|COERCEDUP\\|COERCEFLAG\\|COERCESWAP\\|COLA\\|COLACOLA\\|COLAITE\\|COLANOTcase\\|COLARPITE\\|COLASKIP\\|COLA_EVAL\\|COLAcase\\|COLAthexFCN\\|COMPCONFCRC\\|COMPEVAL\\|CONTEXT\\|CONTEXT!\\|CONTEXT@\\|COPYVAR\\|CRC\\|CREATE\\|CREATEDIR\\|CREATETEMP\\|CRER\\|CRLF\\$\\|CROSSGROB\\|CROSSMARKON\\|CROSS_HAIRS\\|CROSS_OFF\\|CRUNCH\\|CRUNCHNoBlame\\|CSLW5\\|CSRW5\\|CURRENTMARK\\?\\|CURSOR\\+\\|CURSOR@\\|CURSOR_END\\?\\|CURSOR_OFF\\|CURSOR_OFF\\+\\|CURSOR_OFF0\\|CUT\\.EXT\\|CacheStack\\|CharEdit\\|CheckMenuRow\\|CircleB\\|CircleG1\\|CircleG2\\|CircleW\\|CircleXor\\|Ck\\&DecKeyLoc\\|Ck\\&Freeze\\|CkChr00\\|CkEQUtil\\|CkSecoType\\|Clean\\$\\|Clean\\$R0\\|CleanVirtualStack\\|ClearSelection\\|Clr16\\|Clr8\\|Clr8-15\\|ClrAlgEntry\\|ClrAlphaAnn\\|ClrAppMode\\|ClrAppSuspOK\\|ClrDA1Bad\\|ClrDA1IsStat\\|ClrDA1OK\\|ClrDA2OK\\|ClrDA2aBad\\|ClrDA2aOK\\|ClrDA2bBad\\|"

;"CHR_>>\\|CHR_A\\|CHR_Angle\\|CHR_B\\|CHR_C\\|CHR_D\\|CHR_DblQuote\\|CHR_Deriv\\|CHR_E\\|CHR_F\\|CHR_G\\|CHR_H\\|CHR_I\\|CHR_Integral\\|CHR_J\\|CHR_K\\|CHR_L\\|CHR_LeftPar\\|CHR_M\\|CHR_N\\|CHR_Newline\\|CHR_O\\|CHR_P\\|CHR_Pi\\|CHR_Q\\|CHR_R\\|CHR_RightPar\\|CHR_S\\|CHR_Sigma\\|CHR_Space\\|CHR_T\\|CHR_U\\|CHR_UndScore\\|CHR_V\\|CHR_W\\|CHR_X\\|CHR_Y\\|CHR_Z\\|CHR_\\[\\|CHR_\\]\\|CHR_a\\|CHR_b\\|CHR_c\\|CHR_d\\|CHR_e\\|CHR_f\\|CHR_g\\|CHR_h\\|CHR_i\\|CHR_j\\|CHR_k\\|CHR_l\\|CHR_m\\|CHR_n\\|CHR_o\\|CHR_p\\|CHR_q\\|CHR_r\\|CHR_s\\|CHR_t\\|CHR_u\\|CHR_v\\|CHR_w\\|CHR_x\\|CHR_y\\|CHR_z\\|CHR_{\\|CHR_}\\|CINRTN\\|CK\\&DISPATCH0\\|CK\\&DISPATCH1\\|CK\\&DISPATCH2\\|CK0\\|CK0ATTNABORT\\|CK0NOLASTWD\\|CK1\\|CK1\\&Dispatch\\|CK1NOLASTWD\\|CK1NoBlame\\|CK2\\|CK2\\&Dispatch\\|CK2NOLASTWD\\|CK3\\|CK3\\&Dispatch\\|CK3NOLASTWD\\|CK4\\|CK4\\&Dispatch\\|CK4NOLASTWD\\|CK5\\|CK5\\&Dispatch\\|CK5NOLASTWD\\|CKGROBFITS\\|CKLBCRC\\|CKN\\|CKNNOLASTWD\\|CKPICT\\|CKREAL\\|CKREF\\|CKSYMBTYPE\\|CLCD10\\|CLEARLCD\\|CLEARMENU\\|"
"BlankDA2a\\|Box/StdLabel\\|Box/StdLbl:\\|C%%0=\\|C%%1\\|C%%>%%\\|C%%>C%\\|C%%CHS\\|C%%CONJ\\|C%-1\\|C%-1=case\\|C%0\\|C%0=\\|C%0=case\\|C%1\\|C%1/\\|C%1=case\\|C%2=case\\|C%>#\\|C%>%\\|C%>%%\\|C%>%%SWAP\\|C%ABS\\|C%ACOS\\|C%ACOSH\\|C%ALOG\\|C%ARG\\|C%ASIN\\|C%ASINH\\|C%ATAN\\|C%ATANH\\|C%CHS\\|C%CONJ\\|C%COS\\|C%COSH\\|C%C\\^C\\|C%C\\^R\\|C%EXP\\|C%LN\\|C%LOG\\|C%R\\^C\\|C%SGN\\|C%SIN\\|C%SINH\\|C%SQRT\\|C%TAN\\|C%TANH\\|C>Im%\\|C>Re%\\|CACHE\\|CAL_CURS_POS\\|CAL_CURS_POS_VIS\\|CAR$\\|CARCOMP\\|CASEVAL\\|CCSB1\\|CDR\\$\\|CDRCOMP\\|CENTER\\$3x5\\|CENTER\\$5x7\\|CHANGETYPE\\|CHANGE_FLAG\\|CHANGE_FLAG2\\|CHARSEDIT\\|CHECKHEIGHT\\|CHECKKEY\\|CHECKMENU\\|CHECKPICT\\|CHECKPVARS\\|CHECK_SCAN_FONT\\|CHOOSE_INIT\\|CHR>#\\|CHR>\\$\\|CHR_#\\|CHR_\\*\\|CHR_\\+\\|CHR_,\\|CHR_-\\|CHR_->\\|CHR_\\.\\|CHR_\\.\\.\\.\\|CHR_/\\|CHR_0\\|CHR_00\\|CHR_1\\|CHR_2\\|CHR_3\\|CHR_4\\|CHR_5\\|CHR_6\\|CHR_7\\|CHR_8\\|CHR_9\\|CHR_:\\|CHR_;\\|CHR_<\\|CHR_<<\\|CHR_<=\\|CHR_<>\\|CHR_=\\|CHR_>\\|CHR_>=\\|"
;"BINT26\\|BINT27\\|BINT28\\|BINT29\\|BINT3\\|BINT30\\|BINT31\\|BINT32\\|BINT33\\|BINT34\\|BINT35\\|BINT36\\|BINT37\\|BINT38\\|BINT39\\|BINT4\\|BINT40\\|BINT40h\\|BINT41\\|BINT42\\|BINT43\\|BINT44\\|BINT45\\|BINT46\\|BINT47\\|BINT48\\|BINT49\\|BINT5\\|BINT50\\|BINT51\\|BINT52\\|BINT53\\|BINT54\\|BINT55\\|BINT56\\|BINT57\\|BINT58\\|BINT59\\|BINT6\\|BINT60\\|BINT61\\|BINT62\\|BINT63\\|BINT64\\|BINT65\\|BINT66\\|BINT67\\|BINT68\\|BINT69\\|BINT7\\|BINT70\\|BINT71\\|BINT72\\|BINT73\\|BINT74\\|BINT75\\|BINT76\\|BINT77\\|BINT78\\|BINT79\\|BINT8\\|BINT80\\|BINT80h\\|BINT81\\|BINT82\\|BINT83\\|BINT84\\|BINT85\\|BINT86\\|BINT87\\|BINT88\\|BINT89\\|BINT9\\|BINT90\\|BINT91\\|BINT92\\|BINT93\\|BINT94\\|BINT95\\|BINT96\\|BINT97\\|BINT98\\|BINT99\\|BINTC0h\\|BINT_115d\\|BINT_116d\\|BINT_122d\\|BINT_130d\\|BINT_131d\\|BINT_65d\\|BINT_91d\\|BINT_96d\\|BITMAP\\|BLANKIT\\|BLKSWAP\\+\\|BMULT34\\|BOTROW\\|BUILDKPACKET\\|Blank\\$\\|BlankDA1\\|BlankDA12\\|BlankDA2\\|"
;"ANDcase\\|ANNCTRL\\|APNDCRLF\\|APPEND_SPACE\\|APPprompt1!\\|APPprompt2\\|ARRYREAL\\|ASLW5\\|ASRW5\\|ATTN\\?\\|ATTNERR\\|ATTNFLG@\\|ATTNFLGCLR\\|ATTNchk\\|ATTNxcp\\|AUTOSCALE\\|AccessGetID\\|AddLeadingSpace\\|AddTrailingSpace\\|AdjEdModes\\|AlgCharEdit\\|AlgDecomp\\|AlgEntry\\?\\|AlgObEdit\\|AllowIntr\\|AllowPrlcdCl\\|AppDisplay!\\|AppDisplay@\\|AppError!\\|AppError@\\|AppExitCond!\\|AppExitCond@\\|AppKeys!\\|AppKeys0\\|AppMode\\?\\|Arrows\\|AskQuestion\\|AtUserStack\\|Attn#\\|BAK>OB\\|BAKNAME\\|BASE\\|BEGIN\\|BIGDISPN\\|BIGDISPROW1\\|BIGDISPROW2\\|BIGDISPROW3\\|BIGDISPROW4\\|BIND\\|BINT0\\|BINT1\\|BINT10\\|BINT100\\|BINT101\\|BINT102\\|BINT103\\|BINT104\\|BINT105\\|BINT106\\|BINT107\\|BINT108\\|BINT109\\|BINT11\\|BINT110\\|BINT111\\|BINT112\\|BINT113\\|BINT114\\|BINT115\\|BINT116\\|BINT117\\|BINT118\\|BINT119\\|BINT12\\|BINT120\\|BINT121\\|BINT122\\|BINT123\\|BINT124\\|BINT125\\|BINT126\\|BINT127\\|BINT128\\|BINT129\\|BINT13\\|BINT130\\|BINT131\\|BINT14\\|BINT15\\|BINT16\\|BINT17\\|BINT18\\|BINT19\\|BINT2\\|BINT20\\|BINT21\\|BINT22\\|BINT23\\|BINT24\\|BINT25\\|BINT253\\|BINT255d\\|"
;"9GETLAM\\|9PUTLAM\\|::N\\|::NEVAL\\|<DelKey\\|<SkipKey\\|>DelKey\\|>FONT\\|>H\\$\\|>HCOMP\\|>LANGUAGE\\|>LASTRAM-WORD\\|>MINIFONT\\|>R\\|>Review\\$\\|>SkipKey\\|>T\\$\\|>TAG\\|>TCOMP\\|\\?>ROMPTR\\|\\?ACCPTR>\\|\\?ATTNQUIT\\|\\?BlinkCursor\\|\\?CARCOMP\\|\\?CaseKeyDef\\|\\?CaseRomptr@\\|\\?ClrAlg\\|\\?ClrAlgSetPr\\|\\?DispCommandLine\\|\\?DispMenu\\|\\?DispStack\\|\\?DispStatus\\|\\?FlashAlert\\|\\?GOTO\\|\\?Key>UKeyOb\\|\\?OKINALG\\|\\?Ob>Seco\\|\\?PURGE_HERE\\|\\?ROMPTR>\\|\\?SEMI\\|\\?SEMIDROP\\|\\?SKIP\\|\\?SKIPSWAP\\|\\?STO_HERE\\|\\?SWAP\\|\\?SWAPDROP\\|\\?Space/Go>\\|\\?TogU/LCase\\|@\\|@LAM\\|ABND\\|ABORT\\|ABUFF\\|ACCESSBank0\\|ACCESSBank1\\|ACCESSBank10\\|ACCESSBank11\\|ACCESSBank12\\|ACCESSBank13\\|ACCESSBank14\\|ACCESSBank15\\|ACCESSBank2\\|ACCESSBank3\\|ACCESSBank4\\|ACCESSBank5\\|ACCESSBank6\\|ACCESSBank7\\|ACCESSBank8\\|ACCESSBank9\\|ACCESSERAM1\\|ACCESSERAM2\\|ACCESSID1\\|ACCESSID2\\|ACCESSID3\\|ACCESSID4\\|ACCESSID5\\|ACCESSID6\\|ACCESSID7\\|ACCESSIDn\\|ACCESSRAM0\\|ACK_INIT\\|ADDF\\|ADIV3\\|ADIV6\\|ADJMEM\\|ADivC\\|AEQ1stcase\\|AEQopscase\\|AFFICHE\\.REG\\|AFFICHE\\.SBR\\|AFFICHEPIX\\.SBR\\|AGAIN\\|AINRTN\\|ALARM\\?\\|ALARMS@\\|ALARMxcp\\|ALGeq\\?\\|AMULT34\\|AND\\|AND$\\|ANDITE\\|ANDNOTcase\\|"
;"1GETSWAP\\|1LAMBIND\\|1NULLLAM{}\\|1PUTLAM\\|1REV\\|1_#1-SUB\\|1_#1-SUB$\\|1stkdecomp$w\\|2#0=OR\\|2%%>%\\|2%>%%\\|2'RCOLARPITE\\|20GETLAM\\|20PUTLAM\\|21GETLAM\\|21PUTLAM\\|22GETLAM\\|22PUTLAM\\|2@REVAL\\|2DROP\\|2DROP00\\|2DROPFALSE\\|2DUP\\|2DUP#\\+\\|2DUP#<\\|2DUP#=\\|2DUP#>\\|2DUP5ROLL\\|2DUPEQ\\|2DUPSWAP\\|2DropBadKey\\|2EXT\\|2GETEVAL\\|2GETLAM\\|2GROB\\|2HXSLIST\\?\\|2LIST\\|2OVER\\|2Ob>Seco\\|2PUTLAM\\|2RDROP\\|2REAL\\|2SWAP\\|2skipcola\\|3@REVAL\\|3DROP\\|3GETLAM\\|3PICK\\|3PICK#\\+\\|3PICK3PICK\\|3PICKOVER\\|3PICKSWAP\\|3PUTLAM\\|3RDROP\\|3REAL\\|3UNROLL\\|3skipcola\\|4DROP\\|4DropLoop\\|4GETLAM\\|4NULLLAM{}\\|4PICK\\|4PICK#\\+\\|4PICK#\\+SWAP\\|4PICK\\+SWAP\\|4PICKOVER\\|4PICKSWAP\\|4PUTLAM\\|4ROLL\\|4ROLLDROP\\|4ROLLOVER\\|4ROLLROT\\|4ROLLSWAP\\|4UNROLL\\|4UNROLL3DROP\\|4UNROLLDUP\\|4UNROLLROT\\|5DROP\\|5GETLAM\\|5PICK\\|5PUTLAM\\|5ROLL\\|5ROLLDROP\\|5UNROLL\\|5skipcola\\|6DROP\\|6GETLAM\\|6PICK\\|6PUTLAM\\|6ROLL\\|6UNROLL\\|7DROP\\|7GETLAM\\|7PICK\\|7PUTLAM\\|7ROLL\\|7UNROLL\\|8GETLAM\\|8PICK\\|8PUTLAM\\|8ROLL\\|8UNROLL\\|"
;"%CH\\|%CHS\\|%COMB\\|%COS\\|%COSH\\|%D>R\\|%EXP\\|%EXPM1\\|%EXPONENT\\|%FACT\\|%FLOOR\\|%FP\\|%HMS\\+\\|%HMS-\\|%HMS>\\|%IP\\|%IP>#\\|%LN\\|%LNP1\\|%LOG\\|%MANTISSA\\|%MAX\\|%MAXREAL\\|%MAXorder\\|%MIN\\|%MINREAL\\|%MOD\\|%NFACT\\|%NROOT\\|%OF\\|%PERM\\|%PI\\|%POL>%REC\\|%R>D\\|%RAN\\|%RANDOMIZE\\|%REC>%POL\\|%SGN\\|%SIN\\|%SINH\\|%SPH>%REC\\|%SQRT\\|%T\\|%TAN\\|%TANH\\|%\\^\\|%e\\|\\&\\$\\|\\&$SWAP\\|\\&COMP\\|\\&HXS\\|'\\|'DROPFALSE\\|'DoBadKey\\|'DoBadKeyT\\|'ERRJMP\\|'IDFUNCTION\\|'IDPARAMETER\\|'IDPOLAR\\|'IDX\\|'LAMLNAMESTO\\|'LamKPSto\\|'NOP\\|'R\\|'R'R\\|'REVAL\\|'RRDROP\\|'RSAVEWORD\\|'RSaveRomWrd\\|'Rapndit\\|'xDER\\|'xDEREQ\\|\\+LOOP\\|0LASTOWDOB!\\|0LastRomWrd!\\|1/X15\\|10GETLAM\\|10PUTLAM\\|10UNROLL\\|11GETLAM\\|11PUTLAM\\|12GETLAM\\|12PUTLAM\\|13GETLAM\\|13PUTLAM\\|14GETLAM\\|14PUTLAM\\|15GETLAM\\|15PUTLAM\\|16GETLAM\\|16PUTLAM\\|17GETLAM\\|17PUTLAM\\|18GETLAM\\|18PUTLAM\\|19GETLAM\\|19PUTLAM\\|1A/LockA\\|1ABNDSWAP\\|1GETABND\\|1GETLAM\\|1GETLAMSWP1\\+\\|"
;"%%LNP1\\|%%MAX\\|%%P>R\\|%%PI\\|%%R>P\\|%%SIN\\|%%SINDEG\\|%%SINH\\|%%SINRAD\\|%%SQRT\\|%%TANRAD\\|%%\\^\\|%\\*\\|%\\+\\|%\\+SWAP\\|%-\\|%-1\\|%-1=case\\|%-2\\|%-3\\|%-4\\|%-5\\|%-6\\|%-7\\|%-8\\|%-9\\|%-MAXREAL\\|%-MINREAL\\|%\\.1\\|%\\.5\\|%/\\|%0\\|%0<\\|%0<>\\|%0=\\|%0=case\\|%0>\\|%0>=\\|%1\\|%1\\+\\|%1-\\|%1/\\|%10\\|%10\\*\\|%100\\|%11\\|%12\\|%13\\|%14\\|%15\\|%16\\|%17\\|%18\\|%180\\|%19\\|%1=case\\|%2\\|%20\\|%21\\|%22\\|%23\\|%24\\|%25\\|%26\\|%27\\|%2=case\\|%3\\|%360\\|%4\\|%5\\|%6\\|%7\\|%8\\|%80\\|%9\\|%<\\|%<=\\|%<>\\|%=\\|%>\\|%>#\\|%>%%\\|%>%%-\\|%>%%1/\\|%>%%ANGLE\\|%>%%SQRT\\|%>%%SWAP\\|%>=\\|%>C%\\|%>HMS\\|%>TAG\\|%ABS\\|%ABSCOERCE\\|%ACOS\\|%ACOSH\\|%ALOG\\|%ANGLE\\|%ASIN\\|%ASINH\\|%ATAN\\|%ATANH\\|%CEIL\\|"
;"#=case\\|#=casedrop\\|#=casedrpfls\\|#>\\|#>\\$\\|#>1\\|#>2case\\|#>\\?SKIP\\|#>CHR\\|#>HXS\\|#>ITE\\|#>ROMPTR\\|#>case\\|#AND\\|#CAlarmErr\\|#EXITERR\\|#FIVE#FOUR\\|#MAX\\|#MIN\\|#ONE#27\\|#PUSHA-\\|#SyntaxErr\\|#THREE#FOUR\\|#TWO#FOUR\\|#TWO#ONE\\|#TWO#TWO\\|#ZERO#ONE\\|#ZERO#SEVEN\\|#_102\\|\\$1-\\+\\|\\$5x7\\|\\$>GROB\\|\\$>GROBCR\\|\\$>ID\\|\\$>grob\\|\\$>grobCR\\|\\$_''\\|\\$_2DQ\\|\\$_::\\|\\$_<<>>\\|\\$_ECHO\\|\\$_EXIT\\|\\$_GRAD\\|\\$_LRParens\\|\\$_R<<\\|\\$_R<Z\\|\\$_RAD\\|\\$_Undefined\\|\\$_XYZ\\|\\$_\\[\\]\\|\\$_{}\\|%%\\*\\|%%\\*ROT\\|%%\\*SWAP\\|%%\\*UNROT\\|%%\\+\\|%%-\\|%%\\.1\\|%%\\.4\\|%%\\.5\\|%%/\\|%%/>%\\|%%0\\|%%0<\\|%%0<=\\|%%0<>\\|%%0=\\|%%0>\\|%%0>=\\|%%1\\|%%1/\\|%%10\\|%%12\\|%%2\\|%%2PI\\|%%3\\|%%4\\|%%5\\|%%60\\|%%7\\|%%<\\|%%<=\\|%%>\\|%%>%\\|%%>=\\|%%>C%\\|%%ABS\\|%%ACOSRAD\\|%%ANGLE\\|%%ANGLEDEG\\|%%ANGLERAD\\|%%ASINRAD\\|%%CHS\\|%%COS\\|%%COSDEG\\|%%COSH\\|%%COSRAD\\|%%EXP\\|%%FLOOR\\|%%H>HMS\\|%%INT\\|%%LN\\|"
;"!#1\\+IF<dim-1\\|!#1-IF>0\\|!\\*triand\\|!\\*trior\\|!DcompWidth\\|!MATTRNnc\\|!REDIMTEMP\\|!REDIMUSER\\|!append\\$\\|!append\\$SWAP\\|!insert\\$\\|#\\*\\|#\\*OVF\\|#\\+\\|#\\+-1\\|#\\+DUP\\|#\\+OVER\\|#\\+PICK\\|#\\+ROLL\\|#\\+SWAP\\|#\\+UNROLL\\|#-\\|#-#2/\\|#-\\+1\\|#-DUP\\|#-OVER\\|#-PICK\\|#-ROLL\\|#-SWAP\\|#-UNROLL\\|#/\\|#0<>\\|#0=\\|#0=\\?SEMI\\|#0=\\?SKIP\\|#0=ITE\\|#0=UNTIL\\|#0=case\\|#1\\+\\|#1\\+'\\|#1\\+DUP\\|#1\\+LAST\\$\\|#1\\+NDROP\\|#1\\+PICK\\|#1\\+ROLL\\|#1\\+ROT\\|#1\\+SWAP\\|#1\\+UNROLL\\|#1\\+_ONE_DO\\|#1-\\|#1--\\|#1-1SWAP\\|#1-DUP\\|#1-ROT\\|#1-SUB\\$\\|#1-SWAP\\|#1-UNROT\\|#1-{}N\\|#10\\*\\|#10\\+\\|#12\\+\\|#1<>\\|#1=\\|#1=\\?SKIP\\|#1=case\\|#2\\*\\|#2\\+\\|#2\\+PICK\\|#2\\+ROLL\\|#2\\+UNROLL\\|#2-\\|#2/\\|#2<>\\|#2=\\|#3\\+\\|#3\\+PICK\\|#3-\\|#3=\\|#4\\+\\|#4\\+PICK\\|#4-\\|#5\\+\\|#5-\\|#5=\\|#6\\*\\|#6\\+\\|#6-\\|#7\\+\\|#8\\*\\|#8\\+\\|#9\\+\\|#:>\\$\\|#<\\|#<3\\|#<>\\|#<>case\\|#<ITE\\|#<case\\|#=\\|#=\\?SKIP\\|#=ITE\\|#=POSCOMP\\|"
;"!!append\\$\\|!!append\\$\\?\\|!!insert\\$\\|"
	    "\\)\\>"
	    )
	   'font-lock-type-face)
     )
    )
  "Default expressions to highlight in MASD mode."
  )

(put 'masd-mode 'font-lock-defaults '(masd-font-lock-keywords))
      
;;;###autoload
(defun masd-mode ()
  "Major mode for editing MASD files."
  (interactive)
  (kill-all-local-variables)
  (setq major-mode 'masd-mode)
  (setq mode-name "Asm Masd")
  (setq local-abbrev-table masd-mode-abbrev-table)
  (set-syntax-table masd-mode-syntax-table)
  (make-local-variable 'paragraph-start)
  (make-local-variable 'paragraph-separate)
  (setq paragraph-start "$\\|{\\|[ \t\n]*$")
  (setq paragraph-separate "$\\|{\\|[ \t\n\^L]*$")
  (make-local-variable 'comment-start)
  (setq comment-start "%")
  (make-local-variable 'commend-end)
  (setq comment-end "")
  (make-local-variable 'font-lock-defaults)
  (setq font-lock-defaults '(masd-font-lock-keywords nil nil ((?_ . "w"))))
  (run-hooks 'masd-mode-hook))

(provide 'masd)

;;; masd.el ends here